//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 8/28/2022 11:06:07 PM
namespace ManagementOfChangeODataService.Affra.Service.ManagementOfChange.Domain.ManagementOfChanges
{
    /// <summary>
    /// There are no comments for ManagementOfChangeRecordSingle in the schema.
    /// </summary>
    public partial class ManagementOfChangeRecordSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<ManagementOfChangeRecord>
    {
        /// <summary>
        /// Initialize a new ManagementOfChangeRecordSingle object.
        /// </summary>
        public ManagementOfChangeRecordSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new ManagementOfChangeRecordSingle object.
        /// </summary>
        public ManagementOfChangeRecordSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new ManagementOfChangeRecordSingle object.
        /// </summary>
        public ManagementOfChangeRecordSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<ManagementOfChangeRecord> query)
            : base(query) {}

    }
    /// <summary>
    /// There are no comments for ManagementOfChangeRecord in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Id")]
    public partial class ManagementOfChangeRecord : global::Microsoft.OData.Client.BaseEntityType
    {
        /// <summary>
        /// Create a new ManagementOfChangeRecord object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="managementOfChangeField">Initial value of ManagementOfChangeField.</param>
        /// <param name="createdDateTime">Initial value of CreatedDateTime.</param>
        /// <param name="managementOfChangeStatus">Initial value of ManagementOfChangeStatus.</param>
        /// <param name="managementOfChangeCurrentStep">Initial value of ManagementOfChangeCurrentStep.</param>
        /// <param name="xmin">Initial value of xmin.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public static ManagementOfChangeRecord CreateManagementOfChangeRecord(long ID, 
                    global::ManagementOfChangeODataService.Affra.Service.ManagementOfChange.Domain.ManagementOfChanges.ManagementOfChangeField managementOfChangeField, 
                    global::System.DateTimeOffset createdDateTime, 
                    global::ManagementOfChangeODataService.Affra.Service.ManagementOfChange.Domain.ManagementOfChanges.ManagementOfChangeStatus managementOfChangeStatus, 
                    global::ManagementOfChangeODataService.Affra.Service.ManagementOfChange.Domain.ManagementOfChanges.ManagementOfChangeCurrentStep managementOfChangeCurrentStep, 
                    long xmin)
        {
            ManagementOfChangeRecord managementOfChangeRecord = new ManagementOfChangeRecord();
            managementOfChangeRecord.Id = ID;
            managementOfChangeRecord.ManagementOfChangeField = managementOfChangeField;
            managementOfChangeRecord.CreatedDateTime = createdDateTime;
            managementOfChangeRecord.ManagementOfChangeStatus = managementOfChangeStatus;
            managementOfChangeRecord.ManagementOfChangeCurrentStep = managementOfChangeCurrentStep;
            managementOfChangeRecord.xmin = xmin;
            return managementOfChangeRecord;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "Id is required.")]
        public virtual long Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private long _Id;
        partial void OnIdChanging(long value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property TitleOfChange in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        public virtual string TitleOfChange
        {
            get
            {
                return this._TitleOfChange;
            }
            set
            {
                this.OnTitleOfChangeChanging(value);
                this._TitleOfChange = value;
                this.OnTitleOfChangeChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _TitleOfChange;
        partial void OnTitleOfChangeChanging(string value);
        partial void OnTitleOfChangeChanged();
        /// <summary>
        /// There are no comments for Property RecordNumber in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        public virtual string RecordNumber
        {
            get
            {
                return this._RecordNumber;
            }
            set
            {
                this.OnRecordNumberChanging(value);
                this._RecordNumber = value;
                this.OnRecordNumberChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _RecordNumber;
        partial void OnRecordNumberChanging(string value);
        partial void OnRecordNumberChanged();
        /// <summary>
        /// There are no comments for Property ManagementOfChangeField in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "ManagementOfChangeField is required.")]
        public virtual global::ManagementOfChangeODataService.Affra.Service.ManagementOfChange.Domain.ManagementOfChanges.ManagementOfChangeField ManagementOfChangeField
        {
            get
            {
                return this._ManagementOfChangeField;
            }
            set
            {
                this.OnManagementOfChangeFieldChanging(value);
                this._ManagementOfChangeField = value;
                this.OnManagementOfChangeFieldChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::ManagementOfChangeODataService.Affra.Service.ManagementOfChange.Domain.ManagementOfChanges.ManagementOfChangeField _ManagementOfChangeField;
        partial void OnManagementOfChangeFieldChanging(global::ManagementOfChangeODataService.Affra.Service.ManagementOfChange.Domain.ManagementOfChanges.ManagementOfChangeField value);
        partial void OnManagementOfChangeFieldChanged();
        /// <summary>
        /// There are no comments for Property CreatedDateTime in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "CreatedDateTime is required.")]
        public virtual global::System.DateTimeOffset CreatedDateTime
        {
            get
            {
                return this._CreatedDateTime;
            }
            set
            {
                this.OnCreatedDateTimeChanging(value);
                this._CreatedDateTime = value;
                this.OnCreatedDateTimeChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.DateTimeOffset _CreatedDateTime;
        partial void OnCreatedDateTimeChanging(global::System.DateTimeOffset value);
        partial void OnCreatedDateTimeChanged();
        /// <summary>
        /// There are no comments for Property CreatedBy in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        public virtual string CreatedBy
        {
            get
            {
                return this._CreatedBy;
            }
            set
            {
                this.OnCreatedByChanging(value);
                this._CreatedBy = value;
                this.OnCreatedByChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _CreatedBy;
        partial void OnCreatedByChanging(string value);
        partial void OnCreatedByChanged();
        /// <summary>
        /// There are no comments for Property ManagementOfChangeStatus in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "ManagementOfChangeStatus is required.")]
        public virtual global::ManagementOfChangeODataService.Affra.Service.ManagementOfChange.Domain.ManagementOfChanges.ManagementOfChangeStatus ManagementOfChangeStatus
        {
            get
            {
                return this._ManagementOfChangeStatus;
            }
            set
            {
                this.OnManagementOfChangeStatusChanging(value);
                this._ManagementOfChangeStatus = value;
                this.OnManagementOfChangeStatusChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::ManagementOfChangeODataService.Affra.Service.ManagementOfChange.Domain.ManagementOfChanges.ManagementOfChangeStatus _ManagementOfChangeStatus;
        partial void OnManagementOfChangeStatusChanging(global::ManagementOfChangeODataService.Affra.Service.ManagementOfChange.Domain.ManagementOfChanges.ManagementOfChangeStatus value);
        partial void OnManagementOfChangeStatusChanged();
        /// <summary>
        /// There are no comments for Property ManagementOfChangeCurrentStep in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "ManagementOfChangeCurrentStep is required.")]
        public virtual global::ManagementOfChangeODataService.Affra.Service.ManagementOfChange.Domain.ManagementOfChanges.ManagementOfChangeCurrentStep ManagementOfChangeCurrentStep
        {
            get
            {
                return this._ManagementOfChangeCurrentStep;
            }
            set
            {
                this.OnManagementOfChangeCurrentStepChanging(value);
                this._ManagementOfChangeCurrentStep = value;
                this.OnManagementOfChangeCurrentStepChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::ManagementOfChangeODataService.Affra.Service.ManagementOfChange.Domain.ManagementOfChanges.ManagementOfChangeCurrentStep _ManagementOfChangeCurrentStep;
        partial void OnManagementOfChangeCurrentStepChanging(global::ManagementOfChangeODataService.Affra.Service.ManagementOfChange.Domain.ManagementOfChanges.ManagementOfChangeCurrentStep value);
        partial void OnManagementOfChangeCurrentStepChanged();
        /// <summary>
        /// There are no comments for Property Identification in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        public virtual global::ManagementOfChangeODataService.Affra.Service.ManagementOfChange.Domain.Identifications.Identification Identification
        {
            get
            {
                return this._Identification;
            }
            set
            {
                this.OnIdentificationChanging(value);
                this._Identification = value;
                this.OnIdentificationChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::ManagementOfChangeODataService.Affra.Service.ManagementOfChange.Domain.Identifications.Identification _Identification;
        partial void OnIdentificationChanging(global::ManagementOfChangeODataService.Affra.Service.ManagementOfChange.Domain.Identifications.Identification value);
        partial void OnIdentificationChanged();
        /// <summary>
        /// There are no comments for Property RiskEvaluation in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        public virtual global::ManagementOfChangeODataService.Affra.Service.ManagementOfChange.Domain.RiskEvaluations.RiskEvaluation RiskEvaluation
        {
            get
            {
                return this._RiskEvaluation;
            }
            set
            {
                this.OnRiskEvaluationChanging(value);
                this._RiskEvaluation = value;
                this.OnRiskEvaluationChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::ManagementOfChangeODataService.Affra.Service.ManagementOfChange.Domain.RiskEvaluations.RiskEvaluation _RiskEvaluation;
        partial void OnRiskEvaluationChanging(global::ManagementOfChangeODataService.Affra.Service.ManagementOfChange.Domain.RiskEvaluations.RiskEvaluation value);
        partial void OnRiskEvaluationChanged();
        /// <summary>
        /// There are no comments for Property Endorsement in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        public virtual global::ManagementOfChangeODataService.Affra.Service.ManagementOfChange.Domain.Endorsements.Endorsement Endorsement
        {
            get
            {
                return this._Endorsement;
            }
            set
            {
                this.OnEndorsementChanging(value);
                this._Endorsement = value;
                this.OnEndorsementChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::ManagementOfChangeODataService.Affra.Service.ManagementOfChange.Domain.Endorsements.Endorsement _Endorsement;
        partial void OnEndorsementChanging(global::ManagementOfChangeODataService.Affra.Service.ManagementOfChange.Domain.Endorsements.Endorsement value);
        partial void OnEndorsementChanged();
        /// <summary>
        /// There are no comments for Property AuthorisationAndApproval in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        public virtual global::ManagementOfChangeODataService.Affra.Service.ManagementOfChange.Domain.AuthorisationAndApprovals.AuthorisationAndApproval AuthorisationAndApproval
        {
            get
            {
                return this._AuthorisationAndApproval;
            }
            set
            {
                this.OnAuthorisationAndApprovalChanging(value);
                this._AuthorisationAndApproval = value;
                this.OnAuthorisationAndApprovalChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::ManagementOfChangeODataService.Affra.Service.ManagementOfChange.Domain.AuthorisationAndApprovals.AuthorisationAndApproval _AuthorisationAndApproval;
        partial void OnAuthorisationAndApprovalChanging(global::ManagementOfChangeODataService.Affra.Service.ManagementOfChange.Domain.AuthorisationAndApprovals.AuthorisationAndApproval value);
        partial void OnAuthorisationAndApprovalChanged();
        /// <summary>
        /// There are no comments for Property CommunicationAndImplementation in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        public virtual global::ManagementOfChangeODataService.Affra.Service.ManagementOfChange.Domain.CommunicationAndImplementations.CommunicationAndImplementation CommunicationAndImplementation
        {
            get
            {
                return this._CommunicationAndImplementation;
            }
            set
            {
                this.OnCommunicationAndImplementationChanging(value);
                this._CommunicationAndImplementation = value;
                this.OnCommunicationAndImplementationChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::ManagementOfChangeODataService.Affra.Service.ManagementOfChange.Domain.CommunicationAndImplementations.CommunicationAndImplementation _CommunicationAndImplementation;
        partial void OnCommunicationAndImplementationChanging(global::ManagementOfChangeODataService.Affra.Service.ManagementOfChange.Domain.CommunicationAndImplementations.CommunicationAndImplementation value);
        partial void OnCommunicationAndImplementationChanged();
        /// <summary>
        /// There are no comments for Property Extensions in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        public virtual global::System.Collections.ObjectModel.Collection<global::ManagementOfChangeODataService.Affra.Service.ManagementOfChange.Domain.Extensions.Extension> Extensions
        {
            get
            {
                return this._Extensions;
            }
            set
            {
                this.OnExtensionsChanging(value);
                this._Extensions = value;
                this.OnExtensionsChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Collections.ObjectModel.Collection<global::ManagementOfChangeODataService.Affra.Service.ManagementOfChange.Domain.Extensions.Extension> _Extensions = new global::System.Collections.ObjectModel.Collection<global::ManagementOfChangeODataService.Affra.Service.ManagementOfChange.Domain.Extensions.Extension>();
        partial void OnExtensionsChanging(global::System.Collections.ObjectModel.Collection<global::ManagementOfChangeODataService.Affra.Service.ManagementOfChange.Domain.Extensions.Extension> value);
        partial void OnExtensionsChanged();
        /// <summary>
        /// There are no comments for Property CloseOut in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        public virtual global::ManagementOfChangeODataService.Affra.Service.ManagementOfChange.Domain.CloseOuts.CloseOut CloseOut
        {
            get
            {
                return this._CloseOut;
            }
            set
            {
                this.OnCloseOutChanging(value);
                this._CloseOut = value;
                this.OnCloseOutChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::ManagementOfChangeODataService.Affra.Service.ManagementOfChange.Domain.CloseOuts.CloseOut _CloseOut;
        partial void OnCloseOutChanging(global::ManagementOfChangeODataService.Affra.Service.ManagementOfChange.Domain.CloseOuts.CloseOut value);
        partial void OnCloseOutChanged();
        /// <summary>
        /// There are no comments for Property xmin in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "xmin is required.")]
        public virtual long xmin
        {
            get
            {
                return this._xmin;
            }
            set
            {
                this.OnxminChanging(value);
                this._xmin = value;
                this.OnxminChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private long _xmin;
        partial void OnxminChanging(long value);
        partial void OnxminChanged();
    }
    /// <summary>
    /// There are no comments for ManagementOfChangeField in the schema.
    /// </summary>
    public enum ManagementOfChangeField
    {
        HIP = 0,
        LWP = 1,
        Others = 2
    }
    /// <summary>
    /// There are no comments for ManagementOfChangeStatus in the schema.
    /// </summary>
    public enum ManagementOfChangeStatus
    {
        New = 0,
        Pending = 1,
        Extension = 2,
        Completed = 3,
        Deleted = 4
    }
    /// <summary>
    /// There are no comments for ManagementOfChangeCurrentStep in the schema.
    /// </summary>
    public enum ManagementOfChangeCurrentStep
    {
        InitialCreation = 0,
        RiskEvaluation = 1,
        EndorsementSubmitForApproval = 2,
        EndorsementPendingForApproval = 3,
        AuthorisationAndApprovalSubmitForApproval = 4,
        AuthorisationAndApprovalPendingForApproval = 5,
        ExtensionSubmitForApproval = 6,
        ExtensionPendingForApproval = 7,
        CloseOutSubmitForApproval = 8,
        CloseoutPendingForApproval = 9,
        Completed = 10
    }
    /// <summary>
    /// There are no comments for RiskLevels in the schema.
    /// </summary>
    public enum RiskLevels
    {
        LowRisk = 0,
        MediumRisk = 1,
        HighRisk = 2,
        VeryHighRisk = 3
    }
    /// <summary>
    /// Class containing all extension methods
    /// </summary>
    public static class ExtensionMethods
    {
        /// <summary>
        /// Get an entity of type global::ManagementOfChangeODataService.Affra.Service.ManagementOfChange.Domain.ManagementOfChanges.ManagementOfChangeRecord as global::ManagementOfChangeODataService.Affra.Service.ManagementOfChange.Domain.ManagementOfChanges.ManagementOfChangeRecordSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="_keys">dictionary with the names and values of keys</param>
        public static global::ManagementOfChangeODataService.Affra.Service.ManagementOfChange.Domain.ManagementOfChanges.ManagementOfChangeRecordSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::ManagementOfChangeODataService.Affra.Service.ManagementOfChange.Domain.ManagementOfChanges.ManagementOfChangeRecord> _source, global::System.Collections.Generic.IDictionary<string, object> _keys)
        {
            return new global::ManagementOfChangeODataService.Affra.Service.ManagementOfChange.Domain.ManagementOfChanges.ManagementOfChangeRecordSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, _keys)));
        }
        /// <summary>
        /// Get an entity of type global::ManagementOfChangeODataService.Affra.Service.ManagementOfChange.Domain.ManagementOfChanges.ManagementOfChangeRecord as global::ManagementOfChangeODataService.Affra.Service.ManagementOfChange.Domain.ManagementOfChanges.ManagementOfChangeRecordSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="id">The value of id</param>
        public static global::ManagementOfChangeODataService.Affra.Service.ManagementOfChange.Domain.ManagementOfChanges.ManagementOfChangeRecordSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::ManagementOfChangeODataService.Affra.Service.ManagementOfChange.Domain.ManagementOfChanges.ManagementOfChangeRecord> _source,
            long id)
        {
            global::System.Collections.Generic.IDictionary<string, object> _keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "Id", id }
            };
            return new global::ManagementOfChangeODataService.Affra.Service.ManagementOfChange.Domain.ManagementOfChanges.ManagementOfChangeRecordSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, _keys)));
        }
    }
}
namespace ManagementOfChangeODataService.Affra.Service.ManagementOfChange.Domain.Identifications
{
    /// <summary>
    /// There are no comments for Identification in the schema.
    /// </summary>
    public partial class Identification
    {
        /// <summary>
        /// Create a new Identification object.
        /// </summary>
        /// <param name="durationOfChange">Initial value of DurationOfChange.</param>
        /// <param name="expiryDate">Initial value of ExpiryDate.</param>
        /// <param name="reasonForChange">Initial value of ReasonForChange.</param>
        /// <param name="detailOfChange">Initial value of DetailOfChange.</param>
        /// <param name="categoriesOfChange">Initial value of CategoriesOfChange.</param>
        /// <param name="priorityOfChange">Initial value of PriorityOfChange.</param>
        /// <param name="sCEAffected">Initial value of SCEAffected.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public static Identification CreateIdentification(int durationOfChange, 
                    global::System.DateTimeOffset expiryDate, 
                    global::ManagementOfChangeODataService.Affra.Service.ManagementOfChange.Domain.Identifications.ReasonForChange reasonForChange, 
                    global::ManagementOfChangeODataService.Affra.Service.ManagementOfChange.Domain.Identifications.DetailOfChange detailOfChange, 
                    global::ManagementOfChangeODataService.Affra.Service.ManagementOfChange.Domain.Identifications.CategoriesOfChange categoriesOfChange, 
                    global::ManagementOfChangeODataService.Affra.Service.ManagementOfChange.Domain.Identifications.PriorityOfChange priorityOfChange, 
                    bool sCEAffected)
        {
            Identification identification = new Identification();
            identification.DurationOfChange = durationOfChange;
            identification.ExpiryDate = expiryDate;
            identification.ReasonForChange = reasonForChange;
            identification.DetailOfChange = detailOfChange;
            identification.CategoriesOfChange = categoriesOfChange;
            identification.PriorityOfChange = priorityOfChange;
            identification.SCEAffected = sCEAffected;
            return identification;
        }
        /// <summary>
        /// There are no comments for Property DurationOfChange in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "DurationOfChange is required.")]
        public virtual int DurationOfChange
        {
            get
            {
                return this._DurationOfChange;
            }
            set
            {
                this.OnDurationOfChangeChanging(value);
                this._DurationOfChange = value;
                this.OnDurationOfChangeChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private int _DurationOfChange;
        partial void OnDurationOfChangeChanging(int value);
        partial void OnDurationOfChangeChanged();
        /// <summary>
        /// There are no comments for Property ExpiryDate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "ExpiryDate is required.")]
        public virtual global::System.DateTimeOffset ExpiryDate
        {
            get
            {
                return this._ExpiryDate;
            }
            set
            {
                this.OnExpiryDateChanging(value);
                this._ExpiryDate = value;
                this.OnExpiryDateChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.DateTimeOffset _ExpiryDate;
        partial void OnExpiryDateChanging(global::System.DateTimeOffset value);
        partial void OnExpiryDateChanged();
        /// <summary>
        /// There are no comments for Property DescriptionOfChange in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        public virtual string DescriptionOfChange
        {
            get
            {
                return this._DescriptionOfChange;
            }
            set
            {
                this.OnDescriptionOfChangeChanging(value);
                this._DescriptionOfChange = value;
                this.OnDescriptionOfChangeChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _DescriptionOfChange;
        partial void OnDescriptionOfChangeChanging(string value);
        partial void OnDescriptionOfChangeChanged();
        /// <summary>
        /// There are no comments for Property ReasonForChange in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "ReasonForChange is required.")]
        public virtual global::ManagementOfChangeODataService.Affra.Service.ManagementOfChange.Domain.Identifications.ReasonForChange ReasonForChange
        {
            get
            {
                return this._ReasonForChange;
            }
            set
            {
                this.OnReasonForChangeChanging(value);
                this._ReasonForChange = value;
                this.OnReasonForChangeChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::ManagementOfChangeODataService.Affra.Service.ManagementOfChange.Domain.Identifications.ReasonForChange _ReasonForChange;
        partial void OnReasonForChangeChanging(global::ManagementOfChangeODataService.Affra.Service.ManagementOfChange.Domain.Identifications.ReasonForChange value);
        partial void OnReasonForChangeChanged();
        /// <summary>
        /// There are no comments for Property OtherReasonForChange in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        public virtual string OtherReasonForChange
        {
            get
            {
                return this._OtherReasonForChange;
            }
            set
            {
                this.OnOtherReasonForChangeChanging(value);
                this._OtherReasonForChange = value;
                this.OnOtherReasonForChangeChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _OtherReasonForChange;
        partial void OnOtherReasonForChangeChanging(string value);
        partial void OnOtherReasonForChangeChanged();
        /// <summary>
        /// There are no comments for Property DetailOfChange in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "DetailOfChange is required.")]
        public virtual global::ManagementOfChangeODataService.Affra.Service.ManagementOfChange.Domain.Identifications.DetailOfChange DetailOfChange
        {
            get
            {
                return this._DetailOfChange;
            }
            set
            {
                this.OnDetailOfChangeChanging(value);
                this._DetailOfChange = value;
                this.OnDetailOfChangeChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::ManagementOfChangeODataService.Affra.Service.ManagementOfChange.Domain.Identifications.DetailOfChange _DetailOfChange;
        partial void OnDetailOfChangeChanging(global::ManagementOfChangeODataService.Affra.Service.ManagementOfChange.Domain.Identifications.DetailOfChange value);
        partial void OnDetailOfChangeChanged();
        /// <summary>
        /// There are no comments for Property CategoriesOfChange in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "CategoriesOfChange is required.")]
        public virtual global::ManagementOfChangeODataService.Affra.Service.ManagementOfChange.Domain.Identifications.CategoriesOfChange CategoriesOfChange
        {
            get
            {
                return this._CategoriesOfChange;
            }
            set
            {
                this.OnCategoriesOfChangeChanging(value);
                this._CategoriesOfChange = value;
                this.OnCategoriesOfChangeChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::ManagementOfChangeODataService.Affra.Service.ManagementOfChange.Domain.Identifications.CategoriesOfChange _CategoriesOfChange;
        partial void OnCategoriesOfChangeChanging(global::ManagementOfChangeODataService.Affra.Service.ManagementOfChange.Domain.Identifications.CategoriesOfChange value);
        partial void OnCategoriesOfChangeChanged();
        /// <summary>
        /// There are no comments for Property PriorityOfChange in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "PriorityOfChange is required.")]
        public virtual global::ManagementOfChangeODataService.Affra.Service.ManagementOfChange.Domain.Identifications.PriorityOfChange PriorityOfChange
        {
            get
            {
                return this._PriorityOfChange;
            }
            set
            {
                this.OnPriorityOfChangeChanging(value);
                this._PriorityOfChange = value;
                this.OnPriorityOfChangeChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::ManagementOfChangeODataService.Affra.Service.ManagementOfChange.Domain.Identifications.PriorityOfChange _PriorityOfChange;
        partial void OnPriorityOfChangeChanging(global::ManagementOfChangeODataService.Affra.Service.ManagementOfChange.Domain.Identifications.PriorityOfChange value);
        partial void OnPriorityOfChangeChanged();
        /// <summary>
        /// There are no comments for Property SCEAffected in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "SCEAffected is required.")]
        public virtual bool SCEAffected
        {
            get
            {
                return this._SCEAffected;
            }
            set
            {
                this.OnSCEAffectedChanging(value);
                this._SCEAffected = value;
                this.OnSCEAffectedChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private bool _SCEAffected;
        partial void OnSCEAffectedChanging(bool value);
        partial void OnSCEAffectedChanged();
        /// <summary>
        /// There are no comments for Property SCETagNumber in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        public virtual string SCETagNumber
        {
            get
            {
                return this._SCETagNumber;
            }
            set
            {
                this.OnSCETagNumberChanging(value);
                this._SCETagNumber = value;
                this.OnSCETagNumberChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _SCETagNumber;
        partial void OnSCETagNumberChanging(string value);
        partial void OnSCETagNumberChanged();
    }
    /// <summary>
    /// There are no comments for ReasonForChange in the schema.
    /// </summary>
    public enum ReasonForChange
    {
        Deviation = 0,
        Deferment = 1,
        Improvement = 2,
        Deficiency = 3,
        Decommissioning = 4,
        Others = 5
    }
    /// <summary>
    /// There are no comments for DetailOfChange in the schema.
    /// </summary>
    public enum DetailOfChange
    {
        FacilitiesImprovementPlan = 0,
        OperatingChangeAndNonRoutineOperations = 1,
        PlantControlAndSafetySystemChange = 2
    }
    /// <summary>
    /// There are no comments for CategoriesOfChange in the schema.
    /// </summary>
    public enum CategoriesOfChange
    {
        Permanent = 0,
        Temporary = 1
    }
    /// <summary>
    /// There are no comments for PriorityOfChange in the schema.
    /// </summary>
    public enum PriorityOfChange
    {
        Normal = 0,
        Emergency = 1
    }
}
namespace ManagementOfChangeODataService.Affra.Service.ManagementOfChange.Domain.RiskEvaluations
{
    /// <summary>
    /// There are no comments for RiskEvaluation in the schema.
    /// </summary>
    public partial class RiskEvaluation
    {
        /// <summary>
        /// Create a new RiskEvaluation object.
        /// </summary>
        /// <param name="inheritRiskRiskLevel">Initial value of InheritRiskRiskLevel.</param>
        /// <param name="residualRiskRiskLevel">Initial value of ResidualRiskRiskLevel.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public static RiskEvaluation CreateRiskEvaluation(global::ManagementOfChangeODataService.Affra.Service.ManagementOfChange.Domain.ManagementOfChanges.RiskLevels inheritRiskRiskLevel, global::ManagementOfChangeODataService.Affra.Service.ManagementOfChange.Domain.ManagementOfChanges.RiskLevels residualRiskRiskLevel)
        {
            RiskEvaluation riskEvaluation = new RiskEvaluation();
            riskEvaluation.InheritRiskRiskLevel = inheritRiskRiskLevel;
            riskEvaluation.ResidualRiskRiskLevel = residualRiskRiskLevel;
            return riskEvaluation;
        }
        /// <summary>
        /// There are no comments for Property InheritRiskLikelihood in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        public virtual string InheritRiskLikelihood
        {
            get
            {
                return this._InheritRiskLikelihood;
            }
            set
            {
                this.OnInheritRiskLikelihoodChanging(value);
                this._InheritRiskLikelihood = value;
                this.OnInheritRiskLikelihoodChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _InheritRiskLikelihood;
        partial void OnInheritRiskLikelihoodChanging(string value);
        partial void OnInheritRiskLikelihoodChanged();
        /// <summary>
        /// There are no comments for Property InheritRiskConsequence in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        public virtual string InheritRiskConsequence
        {
            get
            {
                return this._InheritRiskConsequence;
            }
            set
            {
                this.OnInheritRiskConsequenceChanging(value);
                this._InheritRiskConsequence = value;
                this.OnInheritRiskConsequenceChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _InheritRiskConsequence;
        partial void OnInheritRiskConsequenceChanging(string value);
        partial void OnInheritRiskConsequenceChanged();
        /// <summary>
        /// There are no comments for Property InheritRiskRiskLevel in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "InheritRiskRiskLevel is required.")]
        public virtual global::ManagementOfChangeODataService.Affra.Service.ManagementOfChange.Domain.ManagementOfChanges.RiskLevels InheritRiskRiskLevel
        {
            get
            {
                return this._InheritRiskRiskLevel;
            }
            set
            {
                this.OnInheritRiskRiskLevelChanging(value);
                this._InheritRiskRiskLevel = value;
                this.OnInheritRiskRiskLevelChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::ManagementOfChangeODataService.Affra.Service.ManagementOfChange.Domain.ManagementOfChanges.RiskLevels _InheritRiskRiskLevel;
        partial void OnInheritRiskRiskLevelChanging(global::ManagementOfChangeODataService.Affra.Service.ManagementOfChange.Domain.ManagementOfChanges.RiskLevels value);
        partial void OnInheritRiskRiskLevelChanged();
        /// <summary>
        /// There are no comments for Property ResidualRiskLikelihood in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        public virtual string ResidualRiskLikelihood
        {
            get
            {
                return this._ResidualRiskLikelihood;
            }
            set
            {
                this.OnResidualRiskLikelihoodChanging(value);
                this._ResidualRiskLikelihood = value;
                this.OnResidualRiskLikelihoodChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _ResidualRiskLikelihood;
        partial void OnResidualRiskLikelihoodChanging(string value);
        partial void OnResidualRiskLikelihoodChanged();
        /// <summary>
        /// There are no comments for Property ResidualRiskConsequence in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        public virtual string ResidualRiskConsequence
        {
            get
            {
                return this._ResidualRiskConsequence;
            }
            set
            {
                this.OnResidualRiskConsequenceChanging(value);
                this._ResidualRiskConsequence = value;
                this.OnResidualRiskConsequenceChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _ResidualRiskConsequence;
        partial void OnResidualRiskConsequenceChanging(string value);
        partial void OnResidualRiskConsequenceChanged();
        /// <summary>
        /// There are no comments for Property ResidualRiskRiskLevel in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "ResidualRiskRiskLevel is required.")]
        public virtual global::ManagementOfChangeODataService.Affra.Service.ManagementOfChange.Domain.ManagementOfChanges.RiskLevels ResidualRiskRiskLevel
        {
            get
            {
                return this._ResidualRiskRiskLevel;
            }
            set
            {
                this.OnResidualRiskRiskLevelChanging(value);
                this._ResidualRiskRiskLevel = value;
                this.OnResidualRiskRiskLevelChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::ManagementOfChangeODataService.Affra.Service.ManagementOfChange.Domain.ManagementOfChanges.RiskLevels _ResidualRiskRiskLevel;
        partial void OnResidualRiskRiskLevelChanging(global::ManagementOfChangeODataService.Affra.Service.ManagementOfChange.Domain.ManagementOfChanges.RiskLevels value);
        partial void OnResidualRiskRiskLevelChanged();
        /// <summary>
        /// There are no comments for Property RecommendationAndCountermeasure in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        public virtual string RecommendationAndCountermeasure
        {
            get
            {
                return this._RecommendationAndCountermeasure;
            }
            set
            {
                this.OnRecommendationAndCountermeasureChanging(value);
                this._RecommendationAndCountermeasure = value;
                this.OnRecommendationAndCountermeasureChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _RecommendationAndCountermeasure;
        partial void OnRecommendationAndCountermeasureChanging(string value);
        partial void OnRecommendationAndCountermeasureChanged();
    }
}
namespace ManagementOfChangeODataService.Affra.Service.ManagementOfChange.Domain.Endorsements
{
    /// <summary>
    /// There are no comments for Endorsement in the schema.
    /// </summary>
    public partial class Endorsement
    {
        /// <summary>
        /// Create a new Endorsement object.
        /// </summary>
        /// <param name="date">Initial value of Date.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public static Endorsement CreateEndorsement(global::System.DateTimeOffset date)
        {
            Endorsement endorsement = new Endorsement();
            endorsement.Date = date;
            return endorsement;
        }
        /// <summary>
        /// There are no comments for Property LineManagerComment in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        public virtual string LineManagerComment
        {
            get
            {
                return this._LineManagerComment;
            }
            set
            {
                this.OnLineManagerCommentChanging(value);
                this._LineManagerComment = value;
                this.OnLineManagerCommentChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _LineManagerComment;
        partial void OnLineManagerCommentChanging(string value);
        partial void OnLineManagerCommentChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        public virtual string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Designation in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        public virtual string Designation
        {
            get
            {
                return this._Designation;
            }
            set
            {
                this.OnDesignationChanging(value);
                this._Designation = value;
                this.OnDesignationChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Designation;
        partial void OnDesignationChanging(string value);
        partial void OnDesignationChanged();
        /// <summary>
        /// There are no comments for Property Signature in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        public virtual string Signature
        {
            get
            {
                return this._Signature;
            }
            set
            {
                this.OnSignatureChanging(value);
                this._Signature = value;
                this.OnSignatureChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Signature;
        partial void OnSignatureChanging(string value);
        partial void OnSignatureChanged();
        /// <summary>
        /// There are no comments for Property Date in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "Date is required.")]
        public virtual global::System.DateTimeOffset Date
        {
            get
            {
                return this._Date;
            }
            set
            {
                this.OnDateChanging(value);
                this._Date = value;
                this.OnDateChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.DateTimeOffset _Date;
        partial void OnDateChanging(global::System.DateTimeOffset value);
        partial void OnDateChanged();
    }
}
namespace ManagementOfChangeODataService.Affra.Service.ManagementOfChange.Domain.AuthorisationAndApprovals
{
    /// <summary>
    /// There are no comments for AuthorisationAndApproval in the schema.
    /// </summary>
    public partial class AuthorisationAndApproval
    {
        /// <summary>
        /// Create a new AuthorisationAndApproval object.
        /// </summary>
        /// <param name="date">Initial value of Date.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public static AuthorisationAndApproval CreateAuthorisationAndApproval(global::System.DateTimeOffset date)
        {
            AuthorisationAndApproval authorisationAndApproval = new AuthorisationAndApproval();
            authorisationAndApproval.Date = date;
            return authorisationAndApproval;
        }
        /// <summary>
        /// There are no comments for Property ApprovingAuthorityComment in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        public virtual string ApprovingAuthorityComment
        {
            get
            {
                return this._ApprovingAuthorityComment;
            }
            set
            {
                this.OnApprovingAuthorityCommentChanging(value);
                this._ApprovingAuthorityComment = value;
                this.OnApprovingAuthorityCommentChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _ApprovingAuthorityComment;
        partial void OnApprovingAuthorityCommentChanging(string value);
        partial void OnApprovingAuthorityCommentChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        public virtual string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Designation in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        public virtual string Designation
        {
            get
            {
                return this._Designation;
            }
            set
            {
                this.OnDesignationChanging(value);
                this._Designation = value;
                this.OnDesignationChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Designation;
        partial void OnDesignationChanging(string value);
        partial void OnDesignationChanged();
        /// <summary>
        /// There are no comments for Property Signature in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        public virtual string Signature
        {
            get
            {
                return this._Signature;
            }
            set
            {
                this.OnSignatureChanging(value);
                this._Signature = value;
                this.OnSignatureChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Signature;
        partial void OnSignatureChanging(string value);
        partial void OnSignatureChanged();
        /// <summary>
        /// There are no comments for Property Date in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "Date is required.")]
        public virtual global::System.DateTimeOffset Date
        {
            get
            {
                return this._Date;
            }
            set
            {
                this.OnDateChanging(value);
                this._Date = value;
                this.OnDateChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.DateTimeOffset _Date;
        partial void OnDateChanging(global::System.DateTimeOffset value);
        partial void OnDateChanged();
    }
}
namespace ManagementOfChangeODataService.Affra.Service.ManagementOfChange.Domain.CommunicationAndImplementations
{
    /// <summary>
    /// There are no comments for CommunicationAndImplementation in the schema.
    /// </summary>
    public partial class CommunicationAndImplementation
    {
        /// <summary>
        /// Create a new CommunicationAndImplementation object.
        /// </summary>
        /// <param name="preparedByDate">Initial value of PreparedByDate.</param>
        /// <param name="agreedByDate">Initial value of AgreedByDate.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public static CommunicationAndImplementation CreateCommunicationAndImplementation(global::System.DateTimeOffset preparedByDate, global::System.DateTimeOffset agreedByDate)
        {
            CommunicationAndImplementation communicationAndImplementation = new CommunicationAndImplementation();
            communicationAndImplementation.PreparedByDate = preparedByDate;
            communicationAndImplementation.AgreedByDate = agreedByDate;
            return communicationAndImplementation;
        }
        /// <summary>
        /// There are no comments for Property Comments in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        public virtual string Comments
        {
            get
            {
                return this._Comments;
            }
            set
            {
                this.OnCommentsChanging(value);
                this._Comments = value;
                this.OnCommentsChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Comments;
        partial void OnCommentsChanging(string value);
        partial void OnCommentsChanged();
        /// <summary>
        /// There are no comments for Property PreparedByName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        public virtual string PreparedByName
        {
            get
            {
                return this._PreparedByName;
            }
            set
            {
                this.OnPreparedByNameChanging(value);
                this._PreparedByName = value;
                this.OnPreparedByNameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _PreparedByName;
        partial void OnPreparedByNameChanging(string value);
        partial void OnPreparedByNameChanged();
        /// <summary>
        /// There are no comments for Property PreparedBySignature in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        public virtual string PreparedBySignature
        {
            get
            {
                return this._PreparedBySignature;
            }
            set
            {
                this.OnPreparedBySignatureChanging(value);
                this._PreparedBySignature = value;
                this.OnPreparedBySignatureChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _PreparedBySignature;
        partial void OnPreparedBySignatureChanging(string value);
        partial void OnPreparedBySignatureChanged();
        /// <summary>
        /// There are no comments for Property PreparedByDate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "PreparedByDate is required.")]
        public virtual global::System.DateTimeOffset PreparedByDate
        {
            get
            {
                return this._PreparedByDate;
            }
            set
            {
                this.OnPreparedByDateChanging(value);
                this._PreparedByDate = value;
                this.OnPreparedByDateChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.DateTimeOffset _PreparedByDate;
        partial void OnPreparedByDateChanging(global::System.DateTimeOffset value);
        partial void OnPreparedByDateChanged();
        /// <summary>
        /// There are no comments for Property AgreedByName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        public virtual string AgreedByName
        {
            get
            {
                return this._AgreedByName;
            }
            set
            {
                this.OnAgreedByNameChanging(value);
                this._AgreedByName = value;
                this.OnAgreedByNameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _AgreedByName;
        partial void OnAgreedByNameChanging(string value);
        partial void OnAgreedByNameChanged();
        /// <summary>
        /// There are no comments for Property AgreedBySignature in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        public virtual string AgreedBySignature
        {
            get
            {
                return this._AgreedBySignature;
            }
            set
            {
                this.OnAgreedBySignatureChanging(value);
                this._AgreedBySignature = value;
                this.OnAgreedBySignatureChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _AgreedBySignature;
        partial void OnAgreedBySignatureChanging(string value);
        partial void OnAgreedBySignatureChanged();
        /// <summary>
        /// There are no comments for Property AgreedByDate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "AgreedByDate is required.")]
        public virtual global::System.DateTimeOffset AgreedByDate
        {
            get
            {
                return this._AgreedByDate;
            }
            set
            {
                this.OnAgreedByDateChanging(value);
                this._AgreedByDate = value;
                this.OnAgreedByDateChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.DateTimeOffset _AgreedByDate;
        partial void OnAgreedByDateChanging(global::System.DateTimeOffset value);
        partial void OnAgreedByDateChanged();
    }
}
namespace ManagementOfChangeODataService.Affra.Service.ManagementOfChange.Domain.Extensions
{
    /// <summary>
    /// There are no comments for Extension in the schema.
    /// </summary>
    public partial class Extension
    {
        /// <summary>
        /// Create a new Extension object.
        /// </summary>
        /// <param name="extensionNo">Initial value of ExtensionNo.</param>
        /// <param name="durationExtended">Initial value of DurationExtended.</param>
        /// <param name="reviewDate">Initial value of ReviewDate.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public static Extension CreateExtension(int extensionNo, int durationExtended, global::System.DateTimeOffset reviewDate)
        {
            Extension extension = new Extension();
            extension.ExtensionNo = extensionNo;
            extension.DurationExtended = durationExtended;
            extension.ReviewDate = reviewDate;
            return extension;
        }
        /// <summary>
        /// There are no comments for Property ExtensionNo in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "ExtensionNo is required.")]
        public virtual int ExtensionNo
        {
            get
            {
                return this._ExtensionNo;
            }
            set
            {
                this.OnExtensionNoChanging(value);
                this._ExtensionNo = value;
                this.OnExtensionNoChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private int _ExtensionNo;
        partial void OnExtensionNoChanging(int value);
        partial void OnExtensionNoChanged();
        /// <summary>
        /// There are no comments for Property DurationExtended in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "DurationExtended is required.")]
        public virtual int DurationExtended
        {
            get
            {
                return this._DurationExtended;
            }
            set
            {
                this.OnDurationExtendedChanging(value);
                this._DurationExtended = value;
                this.OnDurationExtendedChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private int _DurationExtended;
        partial void OnDurationExtendedChanging(int value);
        partial void OnDurationExtendedChanged();
        /// <summary>
        /// There are no comments for Property ReviewDate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "ReviewDate is required.")]
        public virtual global::System.DateTimeOffset ReviewDate
        {
            get
            {
                return this._ReviewDate;
            }
            set
            {
                this.OnReviewDateChanging(value);
                this._ReviewDate = value;
                this.OnReviewDateChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.DateTimeOffset _ReviewDate;
        partial void OnReviewDateChanging(global::System.DateTimeOffset value);
        partial void OnReviewDateChanged();
        /// <summary>
        /// There are no comments for Property ApproverNameColection in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        public virtual string ApproverNameColection
        {
            get
            {
                return this._ApproverNameColection;
            }
            set
            {
                this.OnApproverNameColectionChanging(value);
                this._ApproverNameColection = value;
                this.OnApproverNameColectionChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _ApproverNameColection;
        partial void OnApproverNameColectionChanging(string value);
        partial void OnApproverNameColectionChanged();
        /// <summary>
        /// There are no comments for Property ApproverName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        public virtual string ApproverName
        {
            get
            {
                return this._ApproverName;
            }
            set
            {
                this.OnApproverNameChanging(value);
                this._ApproverName = value;
                this.OnApproverNameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _ApproverName;
        partial void OnApproverNameChanging(string value);
        partial void OnApproverNameChanged();
        /// <summary>
        /// There are no comments for Property ApproverDesignation in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        public virtual string ApproverDesignation
        {
            get
            {
                return this._ApproverDesignation;
            }
            set
            {
                this.OnApproverDesignationChanging(value);
                this._ApproverDesignation = value;
                this.OnApproverDesignationChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _ApproverDesignation;
        partial void OnApproverDesignationChanging(string value);
        partial void OnApproverDesignationChanged();
        /// <summary>
        /// There are no comments for Property ApprovalSignature in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        public virtual string ApprovalSignature
        {
            get
            {
                return this._ApprovalSignature;
            }
            set
            {
                this.OnApprovalSignatureChanging(value);
                this._ApprovalSignature = value;
                this.OnApprovalSignatureChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _ApprovalSignature;
        partial void OnApprovalSignatureChanging(string value);
        partial void OnApprovalSignatureChanged();
    }
}
namespace ManagementOfChangeODataService.Affra.Service.ManagementOfChange.Domain.CloseOuts
{
    /// <summary>
    /// There are no comments for CloseOut in the schema.
    /// </summary>
    public partial class CloseOut
    {
        /// <summary>
        /// Create a new CloseOut object.
        /// </summary>
        /// <param name="closeOutState">Initial value of CloseOutState.</param>
        /// <param name="date">Initial value of Date.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public static CloseOut CreateCloseOut(global::ManagementOfChangeODataService.Affra.Service.ManagementOfChange.Domain.CloseOuts.CloseOutState closeOutState, global::System.DateTimeOffset date)
        {
            CloseOut closeOut = new CloseOut();
            closeOut.CloseOutState = closeOutState;
            closeOut.Date = date;
            return closeOut;
        }
        /// <summary>
        /// There are no comments for Property CloseOutState in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "CloseOutState is required.")]
        public virtual global::ManagementOfChangeODataService.Affra.Service.ManagementOfChange.Domain.CloseOuts.CloseOutState CloseOutState
        {
            get
            {
                return this._CloseOutState;
            }
            set
            {
                this.OnCloseOutStateChanging(value);
                this._CloseOutState = value;
                this.OnCloseOutStateChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::ManagementOfChangeODataService.Affra.Service.ManagementOfChange.Domain.CloseOuts.CloseOutState _CloseOutState;
        partial void OnCloseOutStateChanging(global::ManagementOfChangeODataService.Affra.Service.ManagementOfChange.Domain.CloseOuts.CloseOutState value);
        partial void OnCloseOutStateChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        public virtual string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Designation in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        public virtual string Designation
        {
            get
            {
                return this._Designation;
            }
            set
            {
                this.OnDesignationChanging(value);
                this._Designation = value;
                this.OnDesignationChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Designation;
        partial void OnDesignationChanging(string value);
        partial void OnDesignationChanged();
        /// <summary>
        /// There are no comments for Property Signature in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        public virtual string Signature
        {
            get
            {
                return this._Signature;
            }
            set
            {
                this.OnSignatureChanging(value);
                this._Signature = value;
                this.OnSignatureChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Signature;
        partial void OnSignatureChanging(string value);
        partial void OnSignatureChanged();
        /// <summary>
        /// There are no comments for Property Date in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "Date is required.")]
        public virtual global::System.DateTimeOffset Date
        {
            get
            {
                return this._Date;
            }
            set
            {
                this.OnDateChanging(value);
                this._Date = value;
                this.OnDateChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.DateTimeOffset _Date;
        partial void OnDateChanging(global::System.DateTimeOffset value);
        partial void OnDateChanged();
    }
    /// <summary>
    /// There are no comments for CloseOutState in the schema.
    /// </summary>
    public enum CloseOutState
    {
        RevertOriginalState = 0,
        MadePermanentState = 1
    }
}
namespace ManagementOfChangeODataService.Default
{
    /// <summary>
    /// There are no comments for Container in the schema.
    /// </summary>
    public partial class Container : global::Microsoft.OData.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new Container object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public Container(global::System.Uri serviceRoot) :
                this(serviceRoot, global::Microsoft.OData.Client.ODataProtocolVersion.V4)
        {
        }

        /// <summary>
        /// Initialize a new Container object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public Container(global::System.Uri serviceRoot, global::Microsoft.OData.Client.ODataProtocolVersion protocolVersion) :
                base(serviceRoot, protocolVersion)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
            this.Format.UseJson();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "Affra.Service.ManagementOfChange.Domain.CommunicationAndImplementations", "ManagementOfChangeODataService.Affra.Service.ManagementOfChange.Domain.CommunicationAndImplementations");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            resolvedType = this.DefaultResolveType(typeName, "Affra.Service.ManagementOfChange.Domain.AuthorisationAndApprovals", "ManagementOfChangeODataService.Affra.Service.ManagementOfChange.Domain.AuthorisationAndApprovals");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            resolvedType = this.DefaultResolveType(typeName, "Affra.Service.ManagementOfChange.Domain.ManagementOfChanges", "ManagementOfChangeODataService.Affra.Service.ManagementOfChange.Domain.ManagementOfChanges");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            resolvedType = this.DefaultResolveType(typeName, "Affra.Service.ManagementOfChange.Domain.Identifications", "ManagementOfChangeODataService.Affra.Service.ManagementOfChange.Domain.Identifications");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            resolvedType = this.DefaultResolveType(typeName, "Affra.Service.ManagementOfChange.Domain.RiskEvaluations", "ManagementOfChangeODataService.Affra.Service.ManagementOfChange.Domain.RiskEvaluations");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            resolvedType = this.DefaultResolveType(typeName, "Affra.Service.ManagementOfChange.Domain.Endorsements", "ManagementOfChangeODataService.Affra.Service.ManagementOfChange.Domain.Endorsements");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            resolvedType = this.DefaultResolveType(typeName, "Affra.Service.ManagementOfChange.Domain.Extensions", "ManagementOfChangeODataService.Affra.Service.ManagementOfChange.Domain.Extensions");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            resolvedType = this.DefaultResolveType(typeName, "Affra.Service.ManagementOfChange.Domain.CloseOuts", "ManagementOfChangeODataService.Affra.Service.ManagementOfChange.Domain.CloseOuts");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            resolvedType = this.DefaultResolveType(typeName, "Default", "ManagementOfChangeODataService.Default");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("ManagementOfChangeODataService.Affra.Service.ManagementOfChange.Domain.CommunicationAndImplementations", global::System.StringComparison.Ordinal))
            {
                return string.Concat("Affra.Service.ManagementOfChange.Domain.CommunicationAndImplementations.", clientType.Name);
            }
            if (clientType.Namespace.Equals("ManagementOfChangeODataService.Affra.Service.ManagementOfChange.Domain.AuthorisationAndApprovals", global::System.StringComparison.Ordinal))
            {
                return string.Concat("Affra.Service.ManagementOfChange.Domain.AuthorisationAndApprovals.", clientType.Name);
            }
            if (clientType.Namespace.Equals("ManagementOfChangeODataService.Affra.Service.ManagementOfChange.Domain.ManagementOfChanges", global::System.StringComparison.Ordinal))
            {
                return string.Concat("Affra.Service.ManagementOfChange.Domain.ManagementOfChanges.", clientType.Name);
            }
            if (clientType.Namespace.Equals("ManagementOfChangeODataService.Affra.Service.ManagementOfChange.Domain.Identifications", global::System.StringComparison.Ordinal))
            {
                return string.Concat("Affra.Service.ManagementOfChange.Domain.Identifications.", clientType.Name);
            }
            if (clientType.Namespace.Equals("ManagementOfChangeODataService.Affra.Service.ManagementOfChange.Domain.RiskEvaluations", global::System.StringComparison.Ordinal))
            {
                return string.Concat("Affra.Service.ManagementOfChange.Domain.RiskEvaluations.", clientType.Name);
            }
            if (clientType.Namespace.Equals("ManagementOfChangeODataService.Affra.Service.ManagementOfChange.Domain.Endorsements", global::System.StringComparison.Ordinal))
            {
                return string.Concat("Affra.Service.ManagementOfChange.Domain.Endorsements.", clientType.Name);
            }
            if (clientType.Namespace.Equals("ManagementOfChangeODataService.Affra.Service.ManagementOfChange.Domain.Extensions", global::System.StringComparison.Ordinal))
            {
                return string.Concat("Affra.Service.ManagementOfChange.Domain.Extensions.", clientType.Name);
            }
            if (clientType.Namespace.Equals("ManagementOfChangeODataService.Affra.Service.ManagementOfChange.Domain.CloseOuts", global::System.StringComparison.Ordinal))
            {
                return string.Concat("Affra.Service.ManagementOfChange.Domain.CloseOuts.", clientType.Name);
            }
            if (clientType.Namespace.Equals("ManagementOfChangeODataService.Default", global::System.StringComparison.Ordinal))
            {
                return string.Concat("Default.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for ManagementOfChangeRecord in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::ManagementOfChangeODataService.Affra.Service.ManagementOfChange.Domain.ManagementOfChanges.ManagementOfChangeRecord> ManagementOfChangeRecord
        {
            get
            {
                if ((this._ManagementOfChangeRecord == null))
                {
                    this._ManagementOfChangeRecord = base.CreateQuery<global::ManagementOfChangeODataService.Affra.Service.ManagementOfChange.Domain.ManagementOfChanges.ManagementOfChangeRecord>("ManagementOfChangeRecord");
                }
                return this._ManagementOfChangeRecord;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::ManagementOfChangeODataService.Affra.Service.ManagementOfChange.Domain.ManagementOfChanges.ManagementOfChangeRecord> _ManagementOfChangeRecord;
        /// <summary>
        /// There are no comments for ManagementOfChangeRecord in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual void AddToManagementOfChangeRecord(global::ManagementOfChangeODataService.Affra.Service.ManagementOfChange.Domain.ManagementOfChanges.ManagementOfChangeRecord managementOfChangeRecord)
        {
            base.AddObject("ManagementOfChangeRecord", managementOfChangeRecord);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            private static global::Microsoft.OData.Edm.IEdmModel ParsedModel = LoadModelFromString();

            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            private const string filePath = @"ManagementOfChangeODataServiceCsdl.xml";

            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            public static global::Microsoft.OData.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            private static global::Microsoft.OData.Edm.IEdmModel LoadModelFromString()
            {
                global::System.Xml.XmlReader reader = CreateXmlReader();
                try
                {
                    global::System.Collections.Generic.IEnumerable<global::Microsoft.OData.Edm.Validation.EdmError> errors;
                    global::Microsoft.OData.Edm.IEdmModel edmModel;

                    if (!global::Microsoft.OData.Edm.Csdl.CsdlReader.TryParse(reader, false, out edmModel, out errors))
                    {
	                    global::System.Text.StringBuilder errorMessages = new global::System.Text.StringBuilder();
	                    foreach (var error in errors)
	                    {
		                    errorMessages.Append(error.ErrorMessage);
		                    errorMessages.Append("; ");
	                    }
	                    throw new global::System.InvalidOperationException(errorMessages.ToString());
                    }

                    return edmModel;
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }

            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            private static global::System.Xml.XmlReader CreateXmlReader()
            {
                try
                {
                    var assembly = global::System.Reflection.Assembly.GetExecutingAssembly();
                    var resourcePath = global::System.Linq.Enumerable.Single(assembly.GetManifestResourceNames(), str => str.EndsWith(filePath));
                    global::System.IO.Stream stream = assembly.GetManifestResourceStream(resourcePath);
                    return global::System.Xml.XmlReader.Create(new global::System.IO.StreamReader(stream));
                }
                catch(global::System.Xml.XmlException e)
                {
                    throw new global::System.Xml.XmlException("Failed to create an XmlReader from the stream. Check if the resource exists.", e);
                }
            }
        }
    }
}
