//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JXNippon.CentralizedDatabaseSystem.Shared.ResourceFiles {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JXNippon.CentralizedDatabaseSystem.Shared.ResourceFiles.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis Result.
        /// </summary>
        public static string DailyAnalysisResult {
            get {
                return ResourceManager.GetString("DailyAnalysisResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CI Nalco, EC-1310A (3:7 = CI : Diesel).
        /// </summary>
        public static string DailyCiNalco {
            get {
                return ResourceManager.GetString("DailyCiNalco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DCS, FGS, ASD &amp; Communication System.
        /// </summary>
        public static string DailyCommunicationSystem {
            get {
                return ResourceManager.GetString("DailyCommunicationSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cooling Medium System.
        /// </summary>
        public static string DailyCoolingMediumSystem {
            get {
                return ResourceManager.GetString("DailyCoolingMediumSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De-oiler Injection.
        /// </summary>
        public static string DailyDeOilerInjection {
            get {
                return ResourceManager.GetString("DailyDeOilerInjection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FPSO Production.
        /// </summary>
        public static string DailyFPSOHelangProduction {
            get {
                return ResourceManager.GetString("DailyFPSOHelangProduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FPSO Helang Summary.
        /// </summary>
        public static string DailyFPSOHelangSummary {
            get {
                return ResourceManager.GetString("DailyFPSOHelangSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gas &amp; Condensate Export Sampler &amp; Export Line.
        /// </summary>
        public static string DailyGasCondensateExportSamplerAndExportLine {
            get {
                return ResourceManager.GetString("DailyGasCondensateExportSamplerAndExportLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glycol Pump.
        /// </summary>
        public static string DailyGlycolPump {
            get {
                return ResourceManager.GetString("DailyGlycolPump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glycol Stock.
        /// </summary>
        public static string DailyGlycolStock {
            get {
                return ResourceManager.GetString("DailyGlycolStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glycol Train.
        /// </summary>
        public static string DailyGlycolTrain {
            get {
                return ResourceManager.GetString("DailyGlycolTrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health, Safety &amp; Environment.
        /// </summary>
        public static string DailyHealthSafetyEnvironment {
            get {
                return ResourceManager.GetString("DailyHealthSafetyEnvironment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HIP / LWP Summary.
        /// </summary>
        public static string DailyHIPAndLWPSummary {
            get {
                return ResourceManager.GetString("DailyHIPAndLWPSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HIP Production.
        /// </summary>
        public static string DailyHIPProduction {
            get {
                return ResourceManager.GetString("DailyHIPProduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HIP WellHead Parameter.
        /// </summary>
        public static string DailyHIPWellHeadParameter {
            get {
                return ResourceManager.GetString("DailyHIPWellHeadParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inowac SBN-810 Injection.
        /// </summary>
        public static string DailyInowacInjection {
            get {
                return ResourceManager.GetString("DailyInowacInjection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kawasaki Export Compressor.
        /// </summary>
        public static string DailyKawasakiExportCompressor {
            get {
                return ResourceManager.GetString("DailyKawasakiExportCompressor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LifeBoats.
        /// </summary>
        public static string DailyLifeBoat {
            get {
                return ResourceManager.GetString("DailyLifeBoat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logistic.
        /// </summary>
        public static string DailyLogistic {
            get {
                return ResourceManager.GetString("DailyLogistic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management Of Change (MOC) : Long Term Overrides &amp; Inhibits On Alarm And/Or Trip.
        /// </summary>
        public static string DailyLongTermOverridesInhibitsOnAlarmTrip {
            get {
                return ResourceManager.GetString("DailyLongTermOverridesInhibitsOnAlarmTrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loss Of Primary Containment (LOPC) Incident.
        /// </summary>
        public static string DailyLossOfPrimaryContainmentIncident {
            get {
                return ResourceManager.GetString("DailyLossOfPrimaryContainmentIncident", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layang Wellhead Platform (LWP) Activities.
        /// </summary>
        public static string DailyLWPActivity {
            get {
                return ResourceManager.GetString("DailyLWPActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LWP WellHead Parameter.
        /// </summary>
        public static string DailyLWPWellHeadParameter {
            get {
                return ResourceManager.GetString("DailyLWPWellHeadParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Major Equipment Status.
        /// </summary>
        public static string DailyMajorEquipmentStatus {
            get {
                return ResourceManager.GetString("DailyMajorEquipmentStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximo Work Order.
        /// </summary>
        public static string DailyMaximoWorkOrder {
            get {
                return ResourceManager.GetString("DailyMaximoWorkOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nitrogen Generator.
        /// </summary>
        public static string DailyNitrogenGenerator {
            get {
                return ResourceManager.GetString("DailyNitrogenGenerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management Of Change (MOC) : Operating Change.
        /// </summary>
        public static string DailyOperatingChange {
            get {
                return ResourceManager.GetString("DailyOperatingChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power Generation &amp; Distrubution.
        /// </summary>
        public static string DailyPowerGenerationAndDistribution {
            get {
                return ResourceManager.GetString("DailyPowerGenerationAndDistribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produced Water Treatment System.
        /// </summary>
        public static string DailyProducedWaterTreatmentSystem {
            get {
                return ResourceManager.GetString("DailyProducedWaterTreatmentSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rolls Royce RB211 Engine.
        /// </summary>
        public static string DailyRollsRoyceRB211Engine {
            get {
                return ResourceManager.GetString("DailyRollsRoyceRB211Engine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sand Disposal From TPS (V-3000) via Desander.
        /// </summary>
        public static string DailySandDisposalDesander {
            get {
                return ResourceManager.GetString("DailySandDisposalDesander", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SK10 Production.
        /// </summary>
        public static string DailySK10Production {
            get {
                return ResourceManager.GetString("DailySK10Production", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilities.
        /// </summary>
        public static string DailyUtility {
            get {
                return ResourceManager.GetString("DailyUtility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DailyUtilityBase.
        /// </summary>
        public static string DailyUtilityBase {
            get {
                return ResourceManager.GetString("DailyUtilityBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor Activities.
        /// </summary>
        public static string DailyVendorActivity {
            get {
                return ResourceManager.GetString("DailyVendorActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Water Tank.
        /// </summary>
        public static string DailyWaterTank {
            get {
                return ResourceManager.GetString("DailyWaterTank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wellhead &amp; Separation System.
        /// </summary>
        public static string DailyWellHeadAndSeparationSystem {
            get {
                return ResourceManager.GetString("DailyWellHeadAndSeparationSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Well Stream Cooler.
        /// </summary>
        public static string DailyWellStreamCooler {
            get {
                return ResourceManager.GetString("DailyWellStreamCooler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item exists..
        /// </summary>
        public static string DuplicatePrimaryKey {
            get {
                return ResourceManager.GetString("DuplicatePrimaryKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facilities Improvement Plan.
        /// </summary>
        public static string FacilitiesImprovementPlan {
            get {
                return ResourceManager.GetString("FacilitiesImprovementPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        public static string HighRisk {
            get {
                return ResourceManager.GetString("HighRisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction conflicts with another user..
        /// </summary>
        public static string InvalidToken {
            get {
                return ResourceManager.GetString("InvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        public static string LowRisk {
            get {
                return ResourceManager.GetString("LowRisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This change is hereby made permanent.
        /// </summary>
        public static string MadePermanentState {
            get {
                return ResourceManager.GetString("MadePermanentState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        public static string MediumRisk {
            get {
                return ResourceManager.GetString("MediumRisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item not found..
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operating Change and Non-Routine Operations.
        /// </summary>
        public static string OperatingChangeAndNonRoutineOperations {
            get {
                return ResourceManager.GetString("OperatingChangeAndNonRoutineOperations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plant Control and Safety System Change.
        /// </summary>
        public static string PlantControlAndSafetySystemChange {
            get {
                return ResourceManager.GetString("PlantControlAndSafetySystemChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This change is hereby reverted to original state.
        /// </summary>
        public static string RevertOriginalState {
            get {
                return ResourceManager.GetString("RevertOriginalState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item with the same information already exists..
        /// </summary>
        public static string UniqueKeyViolation {
            get {
                return ResourceManager.GetString("UniqueKeyViolation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error!.
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Risk.
        /// </summary>
        public static string VeryHighRisk {
            get {
                return ResourceManager.GetString("VeryHighRisk", resourceCulture);
            }
        }
    }
}
