//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JXNippon.CentralizedDatabaseSystem.Shared.ResourceFiles {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JXNippon.CentralizedDatabaseSystem.Shared.ResourceFiles.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 [Insignificant].
        /// </summary>
        public static string ConsequenceLevel1 {
            get {
                return ResourceManager.GetString("ConsequenceLevel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 [Minor].
        /// </summary>
        public static string ConsequenceLevel2 {
            get {
                return ResourceManager.GetString("ConsequenceLevel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 [Major].
        /// </summary>
        public static string ConsequenceLevel3 {
            get {
                return ResourceManager.GetString("ConsequenceLevel3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4 [Serious].
        /// </summary>
        public static string ConsequenceLevel4 {
            get {
                return ResourceManager.GetString("ConsequenceLevel4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 [Catastropic].
        /// </summary>
        public static string ConsequenceLevel5 {
            get {
                return ResourceManager.GetString("ConsequenceLevel5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis Result.
        /// </summary>
        public static string DailyAnalysisResult {
            get {
                return ResourceManager.GetString("DailyAnalysisResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CI Nalco, EC-1310A (3:7 = CI : Diesel).
        /// </summary>
        public static string DailyCiNalco {
            get {
                return ResourceManager.GetString("DailyCiNalco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DCS, FGS, ASD &amp; Communication System.
        /// </summary>
        public static string DailyCommunicationSystem {
            get {
                return ResourceManager.GetString("DailyCommunicationSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cooling Medium System.
        /// </summary>
        public static string DailyCoolingMediumSystem {
            get {
                return ResourceManager.GetString("DailyCoolingMediumSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De-oiler Injection.
        /// </summary>
        public static string DailyDeOilerInjection {
            get {
                return ResourceManager.GetString("DailyDeOilerInjection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diesel.
        /// </summary>
        public static string DailyDiesel {
            get {
                return ResourceManager.GetString("DailyDiesel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FPSO Production.
        /// </summary>
        public static string DailyFPSOHelangProduction {
            get {
                return ResourceManager.GetString("DailyFPSOHelangProduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FPSO Helang Summary.
        /// </summary>
        public static string DailyFPSOHelangSummary {
            get {
                return ResourceManager.GetString("DailyFPSOHelangSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gas &amp; Condensate Export Sampler &amp; Export Line.
        /// </summary>
        public static string DailyGasCondensateExportSamplerAndExportLine {
            get {
                return ResourceManager.GetString("DailyGasCondensateExportSamplerAndExportLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glycol Pump.
        /// </summary>
        public static string DailyGlycolPump {
            get {
                return ResourceManager.GetString("DailyGlycolPump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glycol Stock.
        /// </summary>
        public static string DailyGlycolStock {
            get {
                return ResourceManager.GetString("DailyGlycolStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glycol Train.
        /// </summary>
        public static string DailyGlycolTrain {
            get {
                return ResourceManager.GetString("DailyGlycolTrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health, Safety &amp; Environment.
        /// </summary>
        public static string DailyHealthSafetyEnvironment {
            get {
                return ResourceManager.GetString("DailyHealthSafetyEnvironment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HIP / LWP Summary.
        /// </summary>
        public static string DailyHIPAndLWPSummary {
            get {
                return ResourceManager.GetString("DailyHIPAndLWPSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HIP Production.
        /// </summary>
        public static string DailyHIPProduction {
            get {
                return ResourceManager.GetString("DailyHIPProduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HIP WellHead Parameter.
        /// </summary>
        public static string DailyHIPWellHeadParameter {
            get {
                return ResourceManager.GetString("DailyHIPWellHeadParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inowac SBN-810 Injection.
        /// </summary>
        public static string DailyInowacInjection {
            get {
                return ResourceManager.GetString("DailyInowacInjection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kawasaki Export Compressor.
        /// </summary>
        public static string DailyKawasakiExportCompressor {
            get {
                return ResourceManager.GetString("DailyKawasakiExportCompressor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LifeBoats.
        /// </summary>
        public static string DailyLifeBoat {
            get {
                return ResourceManager.GetString("DailyLifeBoat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logistic.
        /// </summary>
        public static string DailyLogistic {
            get {
                return ResourceManager.GetString("DailyLogistic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management Of Change (MOC) : Long Term Overrides &amp; Inhibits On Alarm And/Or Trip.
        /// </summary>
        public static string DailyLongTermOverridesInhibitsOnAlarmTrip {
            get {
                return ResourceManager.GetString("DailyLongTermOverridesInhibitsOnAlarmTrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loss Of Primary Containment (LOPC) Incident.
        /// </summary>
        public static string DailyLossOfPrimaryContainmentIncident {
            get {
                return ResourceManager.GetString("DailyLossOfPrimaryContainmentIncident", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layang Wellhead Platform (LWP) Activities.
        /// </summary>
        public static string DailyLWPActivity {
            get {
                return ResourceManager.GetString("DailyLWPActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LWP WellHead Parameter.
        /// </summary>
        public static string DailyLWPWellHeadParameter {
            get {
                return ResourceManager.GetString("DailyLWPWellHeadParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Major Equipment Status.
        /// </summary>
        public static string DailyMajorEquipmentStatus {
            get {
                return ResourceManager.GetString("DailyMajorEquipmentStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximo Work Order.
        /// </summary>
        public static string DailyMaximoWorkOrder {
            get {
                return ResourceManager.GetString("DailyMaximoWorkOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nitrogen Generator.
        /// </summary>
        public static string DailyNitrogenGenerator {
            get {
                return ResourceManager.GetString("DailyNitrogenGenerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management Of Change (MOC) : Operating Change.
        /// </summary>
        public static string DailyOperatingChange {
            get {
                return ResourceManager.GetString("DailyOperatingChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power Generation &amp; Distrubution.
        /// </summary>
        public static string DailyPowerGenerationAndDistribution {
            get {
                return ResourceManager.GetString("DailyPowerGenerationAndDistribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produced Water Treatment System.
        /// </summary>
        public static string DailyProducedWaterTreatmentSystem {
            get {
                return ResourceManager.GetString("DailyProducedWaterTreatmentSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rolls Royce RB211 Engine.
        /// </summary>
        public static string DailyRollsRoyceRB211Engine {
            get {
                return ResourceManager.GetString("DailyRollsRoyceRB211Engine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sand Disposal From TPS (V-3000) via Desander.
        /// </summary>
        public static string DailySandDisposalDesander {
            get {
                return ResourceManager.GetString("DailySandDisposalDesander", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SK10 Production.
        /// </summary>
        public static string DailySK10Production {
            get {
                return ResourceManager.GetString("DailySK10Production", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilities.
        /// </summary>
        public static string DailyUtility {
            get {
                return ResourceManager.GetString("DailyUtility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DailyUtilityBase.
        /// </summary>
        public static string DailyUtilityBase {
            get {
                return ResourceManager.GetString("DailyUtilityBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor Activities.
        /// </summary>
        public static string DailyVendorActivity {
            get {
                return ResourceManager.GetString("DailyVendorActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Water Tank.
        /// </summary>
        public static string DailyWaterTank {
            get {
                return ResourceManager.GetString("DailyWaterTank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wellhead &amp; Separation System.
        /// </summary>
        public static string DailyWellHeadAndSeparationSystem {
            get {
                return ResourceManager.GetString("DailyWellHeadAndSeparationSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Well Stream Cooler.
        /// </summary>
        public static string DailyWellStreamCooler {
            get {
                return ResourceManager.GetString("DailyWellStreamCooler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item exists..
        /// </summary>
        public static string DuplicatePrimaryKey {
            get {
                return ResourceManager.GetString("DuplicatePrimaryKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E1: PETRONAS.
        /// </summary>
        public static string E1 {
            get {
                return ResourceManager.GetString("E1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E2: Customer.
        /// </summary>
        public static string E2 {
            get {
                return ResourceManager.GetString("E2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E3: Cascaded Shutdown.
        /// </summary>
        public static string E3 {
            get {
                return ResourceManager.GetString("E3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E4: Others.
        /// </summary>
        public static string E4 {
            get {
                return ResourceManager.GetString("E4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facilities Improvement Plan.
        /// </summary>
        public static string FacilitiesImprovementPlan {
            get {
                return ResourceManager.GetString("FacilitiesImprovementPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        public static string HighRisk {
            get {
                return ResourceManager.GetString("HighRisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction conflicts with another user..
        /// </summary>
        public static string InvalidToken {
            get {
                return ResourceManager.GetString("InvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A [Remotely likely to].
        /// </summary>
        public static string LikelihoodLevelA {
            get {
                return ResourceManager.GetString("LikelihoodLevelA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B [Unlikely].
        /// </summary>
        public static string LikelihoodLevelB {
            get {
                return ResourceManager.GetString("LikelihoodLevelB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C [Possible].
        /// </summary>
        public static string LikelihoodLevelC {
            get {
                return ResourceManager.GetString("LikelihoodLevelC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D [Likely].
        /// </summary>
        public static string LikelihoodLevelD {
            get {
                return ResourceManager.GetString("LikelihoodLevelD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E [Almost Certain].
        /// </summary>
        public static string LikelihoodLevelE {
            get {
                return ResourceManager.GetString("LikelihoodLevelE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        public static string LowRisk {
            get {
                return ResourceManager.GetString("LowRisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This change is hereby made permanent.
        /// </summary>
        public static string MadePermanentState {
            get {
                return ResourceManager.GetString("MadePermanentState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        public static string MediumRisk {
            get {
                return ResourceManager.GetString("MediumRisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item not found..
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O1: Production Enhancement.
        /// </summary>
        public static string O1 {
            get {
                return ResourceManager.GetString("O1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O2: Wireline.
        /// </summary>
        public static string O2 {
            get {
                return ResourceManager.GetString("O2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O3: Offloading operations.
        /// </summary>
        public static string O3 {
            get {
                return ResourceManager.GetString("O3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O4: Production operations.
        /// </summary>
        public static string O4 {
            get {
                return ResourceManager.GetString("O4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O5: Inspection &amp; Maintenance.
        /// </summary>
        public static string O5 {
            get {
                return ResourceManager.GetString("O5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O6: Construction.
        /// </summary>
        public static string O6 {
            get {
                return ResourceManager.GetString("O6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operating Change and Non-Routine Operations.
        /// </summary>
        public static string OperatingChangeAndNonRoutineOperations {
            get {
                return ResourceManager.GetString("OperatingChangeAndNonRoutineOperations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planned.
        /// </summary>
        public static string P {
            get {
                return ResourceManager.GetString("P", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P1: Separation.
        /// </summary>
        public static string P1 {
            get {
                return ResourceManager.GetString("P1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P2: Gas dehydration.
        /// </summary>
        public static string P2 {
            get {
                return ResourceManager.GetString("P2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P3: Safeguarding &amp; control system.
        /// </summary>
        public static string P3 {
            get {
                return ResourceManager.GetString("P3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P4: Metering.
        /// </summary>
        public static string P4 {
            get {
                return ResourceManager.GetString("P4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P5: Produced water.
        /// </summary>
        public static string P5 {
            get {
                return ResourceManager.GetString("P5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P6: Pipeline.
        /// </summary>
        public static string P6 {
            get {
                return ResourceManager.GetString("P6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P7: Storage &amp; Offloading.
        /// </summary>
        public static string P7 {
            get {
                return ResourceManager.GetString("P7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P8: Utilities.
        /// </summary>
        public static string P8 {
            get {
                return ResourceManager.GetString("P8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planned Downtime.
        /// </summary>
        public static string PlannedDowntime {
            get {
                return ResourceManager.GetString("PlannedDowntime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plant Control and Safety System Change.
        /// </summary>
        public static string PlantControlAndSafetySystemChange {
            get {
                return ResourceManager.GetString("PlantControlAndSafetySystemChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R1: Export compression.
        /// </summary>
        public static string R1 {
            get {
                return ResourceManager.GetString("R1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R2: Gas lift compression.
        /// </summary>
        public static string R2 {
            get {
                return ResourceManager.GetString("R2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R3: Power generation.
        /// </summary>
        public static string R3 {
            get {
                return ResourceManager.GetString("R3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R4: Export pumps.
        /// </summary>
        public static string R4 {
            get {
                return ResourceManager.GetString("R4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This change is hereby reverted to original state.
        /// </summary>
        public static string RevertOriginalState {
            get {
                return ResourceManager.GetString("RevertOriginalState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unplanned.
        /// </summary>
        public static string U {
            get {
                return ResourceManager.GetString("U", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item with the same information already exists..
        /// </summary>
        public static string UniqueKeyViolation {
            get {
                return ResourceManager.GetString("UniqueKeyViolation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error!.
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unplanned Downtime.
        /// </summary>
        public static string UnplannedDowntime {
            get {
                return ResourceManager.GetString("UnplannedDowntime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Risk.
        /// </summary>
        public static string VeryHighRisk {
            get {
                return ResourceManager.GetString("VeryHighRisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W1: Reservoir Conditions.
        /// </summary>
        public static string W1 {
            get {
                return ResourceManager.GetString("W1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W2: Well Conditions.
        /// </summary>
        public static string W2 {
            get {
                return ResourceManager.GetString("W2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W3: Artificial Lift.
        /// </summary>
        public static string W3 {
            get {
                return ResourceManager.GetString("W3", resourceCulture);
            }
        }
    }
}
