//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 11/6/2022 1:40:59 PM
namespace ViewODataService.Affra.Service.View.Domain.Views
{
    /// <summary>
    /// There are no comments for ViewSingle in the schema.
    /// </summary>
    public partial class ViewSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<View>
    {
        /// <summary>
        /// Initialize a new ViewSingle object.
        /// </summary>
        public ViewSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new ViewSingle object.
        /// </summary>
        public ViewSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new ViewSingle object.
        /// </summary>
        public ViewSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<View> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for Rows in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::ViewODataService.Affra.Service.View.Domain.Views.Row> Rows
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Rows == null))
                {
                    this._Rows = Context.CreateQuery<global::ViewODataService.Affra.Service.View.Domain.Views.Row>(GetPath("Rows"));
                }
                return this._Rows;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::ViewODataService.Affra.Service.View.Domain.Views.Row> _Rows;
    }
    /// <summary>
    /// There are no comments for View in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Id")]
    public partial class View : global::Microsoft.OData.Client.BaseEntityType
    {
        /// <summary>
        /// Create a new View object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="name">Initial value of Name.</param>
        /// <param name="xmin">Initial value of xmin.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        public static View CreateView(long ID, string name, long xmin)
        {
            View view = new View();
            view.Id = ID;
            view.Name = name;
            view.xmin = xmin;
            return view;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        public long Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        private long _Id;
        partial void OnIdChanging(long value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property xmin in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        public long xmin
        {
            get
            {
                return this._xmin;
            }
            set
            {
                this.OnxminChanging(value);
                this._xmin = value;
                this.OnxminChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        private long _xmin;
        partial void OnxminChanging(long value);
        partial void OnxminChanged();
        /// <summary>
        /// There are no comments for Property Rows in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        public global::System.Collections.ObjectModel.Collection<global::ViewODataService.Affra.Service.View.Domain.Views.Row> Rows
        {
            get
            {
                return this._Rows;
            }
            set
            {
                this.OnRowsChanging(value);
                this._Rows = value;
                this.OnRowsChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        private global::System.Collections.ObjectModel.Collection<global::ViewODataService.Affra.Service.View.Domain.Views.Row> _Rows = new global::System.Collections.ObjectModel.Collection<global::ViewODataService.Affra.Service.View.Domain.Views.Row>();
        partial void OnRowsChanging(global::System.Collections.ObjectModel.Collection<global::ViewODataService.Affra.Service.View.Domain.Views.Row> value);
        partial void OnRowsChanged();
    }
    /// <summary>
    /// There are no comments for RowSingle in the schema.
    /// </summary>
    public partial class RowSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Row>
    {
        /// <summary>
        /// Initialize a new RowSingle object.
        /// </summary>
        public RowSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new RowSingle object.
        /// </summary>
        public RowSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new RowSingle object.
        /// </summary>
        public RowSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<Row> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for View in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        public global::ViewODataService.Affra.Service.View.Domain.Views.ViewSingle View
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._View == null))
                {
                    this._View = new global::ViewODataService.Affra.Service.View.Domain.Views.ViewSingle(this.Context, GetPath("View"));
                }
                return this._View;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        private global::ViewODataService.Affra.Service.View.Domain.Views.ViewSingle _View;
        /// <summary>
        /// There are no comments for Columns in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::ViewODataService.Affra.Service.View.Domain.Views.Column> Columns
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Columns == null))
                {
                    this._Columns = Context.CreateQuery<global::ViewODataService.Affra.Service.View.Domain.Views.Column>(GetPath("Columns"));
                }
                return this._Columns;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::ViewODataService.Affra.Service.View.Domain.Views.Column> _Columns;
    }
    /// <summary>
    /// There are no comments for Row in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Id")]
    public partial class Row : global::Microsoft.OData.Client.BaseEntityType
    {
        /// <summary>
        /// Create a new Row object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="sequence">Initial value of Sequence.</param>
        /// <param name="viewName">Initial value of ViewName.</param>
        /// <param name="xmin">Initial value of xmin.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        public static Row CreateRow(long ID, int sequence, string viewName, long xmin)
        {
            Row row = new Row();
            row.Id = ID;
            row.Sequence = sequence;
            row.ViewName = viewName;
            row.xmin = xmin;
            return row;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        public long Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        private long _Id;
        partial void OnIdChanging(long value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Sequence in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        public int Sequence
        {
            get
            {
                return this._Sequence;
            }
            set
            {
                this.OnSequenceChanging(value);
                this._Sequence = value;
                this.OnSequenceChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        private int _Sequence;
        partial void OnSequenceChanging(int value);
        partial void OnSequenceChanged();
        /// <summary>
        /// There are no comments for Property ViewName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        public string ViewName
        {
            get
            {
                return this._ViewName;
            }
            set
            {
                this.OnViewNameChanging(value);
                this._ViewName = value;
                this.OnViewNameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        private string _ViewName;
        partial void OnViewNameChanging(string value);
        partial void OnViewNameChanged();
        /// <summary>
        /// There are no comments for Property xmin in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        public long xmin
        {
            get
            {
                return this._xmin;
            }
            set
            {
                this.OnxminChanging(value);
                this._xmin = value;
                this.OnxminChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        private long _xmin;
        partial void OnxminChanging(long value);
        partial void OnxminChanged();
        /// <summary>
        /// There are no comments for Property View in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        public global::ViewODataService.Affra.Service.View.Domain.Views.View View
        {
            get
            {
                return this._View;
            }
            set
            {
                this.OnViewChanging(value);
                this._View = value;
                this.OnViewChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        private global::ViewODataService.Affra.Service.View.Domain.Views.View _View;
        partial void OnViewChanging(global::ViewODataService.Affra.Service.View.Domain.Views.View value);
        partial void OnViewChanged();
        /// <summary>
        /// There are no comments for Property Columns in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        public global::System.Collections.ObjectModel.Collection<global::ViewODataService.Affra.Service.View.Domain.Views.Column> Columns
        {
            get
            {
                return this._Columns;
            }
            set
            {
                this.OnColumnsChanging(value);
                this._Columns = value;
                this.OnColumnsChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        private global::System.Collections.ObjectModel.Collection<global::ViewODataService.Affra.Service.View.Domain.Views.Column> _Columns = new global::System.Collections.ObjectModel.Collection<global::ViewODataService.Affra.Service.View.Domain.Views.Column>();
        partial void OnColumnsChanging(global::System.Collections.ObjectModel.Collection<global::ViewODataService.Affra.Service.View.Domain.Views.Column> value);
        partial void OnColumnsChanged();
    }
    /// <summary>
    /// There are no comments for ColumnSingle in the schema.
    /// </summary>
    public partial class ColumnSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Column>
    {
        /// <summary>
        /// Initialize a new ColumnSingle object.
        /// </summary>
        public ColumnSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new ColumnSingle object.
        /// </summary>
        public ColumnSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new ColumnSingle object.
        /// </summary>
        public ColumnSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<Column> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for Row in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        public global::ViewODataService.Affra.Service.View.Domain.Views.RowSingle Row
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Row == null))
                {
                    this._Row = new global::ViewODataService.Affra.Service.View.Domain.Views.RowSingle(this.Context, GetPath("Row"));
                }
                return this._Row;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        private global::ViewODataService.Affra.Service.View.Domain.Views.RowSingle _Row;
        /// <summary>
        /// There are no comments for View in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        public global::ViewODataService.Affra.Service.View.Domain.Views.ViewSingle View
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._View == null))
                {
                    this._View = new global::ViewODataService.Affra.Service.View.Domain.Views.ViewSingle(this.Context, GetPath("View"));
                }
                return this._View;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        private global::ViewODataService.Affra.Service.View.Domain.Views.ViewSingle _View;
    }
    /// <summary>
    /// There are no comments for Column in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Id")]
    public partial class Column : global::Microsoft.OData.Client.BaseEntityType
    {
        /// <summary>
        /// Create a new Column object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="sequence">Initial value of Sequence.</param>
        /// <param name="viewName">Initial value of ViewName.</param>
        /// <param name="xmin">Initial value of xmin.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        public static Column CreateColumn(long ID, int sequence, string viewName, long xmin)
        {
            Column column = new Column();
            column.Id = ID;
            column.Sequence = sequence;
            column.ViewName = viewName;
            column.xmin = xmin;
            return column;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        public long Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        private long _Id;
        partial void OnIdChanging(long value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Sequence in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        public int Sequence
        {
            get
            {
                return this._Sequence;
            }
            set
            {
                this.OnSequenceChanging(value);
                this._Sequence = value;
                this.OnSequenceChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        private int _Sequence;
        partial void OnSequenceChanging(int value);
        partial void OnSequenceChanged();
        /// <summary>
        /// There are no comments for Property RowId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        public global::System.Nullable<long> RowId
        {
            get
            {
                return this._RowId;
            }
            set
            {
                this.OnRowIdChanging(value);
                this._RowId = value;
                this.OnRowIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        private global::System.Nullable<long> _RowId;
        partial void OnRowIdChanging(global::System.Nullable<long> value);
        partial void OnRowIdChanged();
        /// <summary>
        /// There are no comments for Property ComponentType in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        public string ComponentType
        {
            get
            {
                return this._ComponentType;
            }
            set
            {
                this.OnComponentTypeChanging(value);
                this._ComponentType = value;
                this.OnComponentTypeChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        private string _ComponentType;
        partial void OnComponentTypeChanging(string value);
        partial void OnComponentTypeChanged();
        /// <summary>
        /// There are no comments for Property ColumnComponent in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        public string ColumnComponent
        {
            get
            {
                return this._ColumnComponent;
            }
            set
            {
                this.OnColumnComponentChanging(value);
                this._ColumnComponent = value;
                this.OnColumnComponentChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        private string _ColumnComponent;
        partial void OnColumnComponentChanging(string value);
        partial void OnColumnComponentChanged();
        /// <summary>
        /// There are no comments for Property ViewName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        public string ViewName
        {
            get
            {
                return this._ViewName;
            }
            set
            {
                this.OnViewNameChanging(value);
                this._ViewName = value;
                this.OnViewNameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        private string _ViewName;
        partial void OnViewNameChanging(string value);
        partial void OnViewNameChanged();
        /// <summary>
        /// There are no comments for Property xmin in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        public long xmin
        {
            get
            {
                return this._xmin;
            }
            set
            {
                this.OnxminChanging(value);
                this._xmin = value;
                this.OnxminChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        private long _xmin;
        partial void OnxminChanging(long value);
        partial void OnxminChanged();
        /// <summary>
        /// There are no comments for Property Row in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        public global::ViewODataService.Affra.Service.View.Domain.Views.Row Row
        {
            get
            {
                return this._Row;
            }
            set
            {
                this.OnRowChanging(value);
                this._Row = value;
                this.OnRowChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        private global::ViewODataService.Affra.Service.View.Domain.Views.Row _Row;
        partial void OnRowChanging(global::ViewODataService.Affra.Service.View.Domain.Views.Row value);
        partial void OnRowChanged();
        /// <summary>
        /// There are no comments for Property View in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        public global::ViewODataService.Affra.Service.View.Domain.Views.View View
        {
            get
            {
                return this._View;
            }
            set
            {
                this.OnViewChanging(value);
                this._View = value;
                this.OnViewChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        private global::ViewODataService.Affra.Service.View.Domain.Views.View _View;
        partial void OnViewChanging(global::ViewODataService.Affra.Service.View.Domain.Views.View value);
        partial void OnViewChanged();
    }
    /// <summary>
    /// Class containing all extension methods
    /// </summary>
    public static class ExtensionMethods
    {
        /// <summary>
        /// Get an entity of type global::ViewODataService.Affra.Service.View.Domain.Views.View as global::ViewODataService.Affra.Service.View.Domain.Views.ViewSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::ViewODataService.Affra.Service.View.Domain.Views.ViewSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::ViewODataService.Affra.Service.View.Domain.Views.View> _source, global::System.Collections.Generic.IDictionary<string, object> keys)
        {
            return new global::ViewODataService.Affra.Service.View.Domain.Views.ViewSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::ViewODataService.Affra.Service.View.Domain.Views.View as global::ViewODataService.Affra.Service.View.Domain.Views.ViewSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="id">The value of id</param>
        public static global::ViewODataService.Affra.Service.View.Domain.Views.ViewSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::ViewODataService.Affra.Service.View.Domain.Views.View> _source,
            long id)
        {
            global::System.Collections.Generic.IDictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "Id", id }
            };
            return new global::ViewODataService.Affra.Service.View.Domain.Views.ViewSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::ViewODataService.Affra.Service.View.Domain.Views.Row as global::ViewODataService.Affra.Service.View.Domain.Views.RowSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::ViewODataService.Affra.Service.View.Domain.Views.RowSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::ViewODataService.Affra.Service.View.Domain.Views.Row> _source, global::System.Collections.Generic.IDictionary<string, object> keys)
        {
            return new global::ViewODataService.Affra.Service.View.Domain.Views.RowSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::ViewODataService.Affra.Service.View.Domain.Views.Row as global::ViewODataService.Affra.Service.View.Domain.Views.RowSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="id">The value of id</param>
        public static global::ViewODataService.Affra.Service.View.Domain.Views.RowSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::ViewODataService.Affra.Service.View.Domain.Views.Row> _source,
            long id)
        {
            global::System.Collections.Generic.IDictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "Id", id }
            };
            return new global::ViewODataService.Affra.Service.View.Domain.Views.RowSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::ViewODataService.Affra.Service.View.Domain.Views.Column as global::ViewODataService.Affra.Service.View.Domain.Views.ColumnSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::ViewODataService.Affra.Service.View.Domain.Views.ColumnSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::ViewODataService.Affra.Service.View.Domain.Views.Column> _source, global::System.Collections.Generic.IDictionary<string, object> keys)
        {
            return new global::ViewODataService.Affra.Service.View.Domain.Views.ColumnSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::ViewODataService.Affra.Service.View.Domain.Views.Column as global::ViewODataService.Affra.Service.View.Domain.Views.ColumnSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="id">The value of id</param>
        public static global::ViewODataService.Affra.Service.View.Domain.Views.ColumnSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::ViewODataService.Affra.Service.View.Domain.Views.Column> _source,
            long id)
        {
            global::System.Collections.Generic.IDictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "Id", id }
            };
            return new global::ViewODataService.Affra.Service.View.Domain.Views.ColumnSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, keys)));
        }
    }
}
namespace ViewODataService.Default
{
    /// <summary>
    /// There are no comments for Container in the schema.
    /// </summary>
    public partial class Container : global::Microsoft.OData.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new Container object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        public Container(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::Microsoft.OData.Client.ODataProtocolVersion.V4)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
            this.Format.UseJson();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "Affra.Service.View.Domain.Views", "ViewODataService.Affra.Service.View.Domain.Views");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            resolvedType = this.DefaultResolveType(typeName, "Default", "ViewODataService.Default");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("ViewODataService.Affra.Service.View.Domain.Views", global::System.StringComparison.Ordinal))
            {
                return string.Concat("Affra.Service.View.Domain.Views.", clientType.Name);
            }
            if (clientType.Namespace.Equals("ViewODataService.Default", global::System.StringComparison.Ordinal))
            {
                return string.Concat("Default.", clientType.Name);
            }
            return clientType.FullName;
        }
        /// <summary>
        /// There are no comments for View in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::ViewODataService.Affra.Service.View.Domain.Views.View> View
        {
            get
            {
                if ((this._View == null))
                {
                    this._View = base.CreateQuery<global::ViewODataService.Affra.Service.View.Domain.Views.View>("View");
                }
                return this._View;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::ViewODataService.Affra.Service.View.Domain.Views.View> _View;
        /// <summary>
        /// There are no comments for Row in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::ViewODataService.Affra.Service.View.Domain.Views.Row> Row
        {
            get
            {
                if ((this._Row == null))
                {
                    this._Row = base.CreateQuery<global::ViewODataService.Affra.Service.View.Domain.Views.Row>("Row");
                }
                return this._Row;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::ViewODataService.Affra.Service.View.Domain.Views.Row> _Row;
        /// <summary>
        /// There are no comments for Column in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::ViewODataService.Affra.Service.View.Domain.Views.Column> Column
        {
            get
            {
                if ((this._Column == null))
                {
                    this._Column = base.CreateQuery<global::ViewODataService.Affra.Service.View.Domain.Views.Column>("Column");
                }
                return this._Column;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::ViewODataService.Affra.Service.View.Domain.Views.Column> _Column;
        /// <summary>
        /// There are no comments for View in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        public void AddToView(global::ViewODataService.Affra.Service.View.Domain.Views.View view)
        {
            base.AddObject("View", view);
        }
        /// <summary>
        /// There are no comments for Row in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        public void AddToRow(global::ViewODataService.Affra.Service.View.Domain.Views.Row row)
        {
            base.AddObject("Row", row);
        }
        /// <summary>
        /// There are no comments for Column in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        public void AddToColumn(global::ViewODataService.Affra.Service.View.Domain.Views.Column column)
        {
            base.AddObject("Column", column);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
            private static global::Microsoft.OData.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
            private const string Edmx = @"<edmx:Edmx Version=""4.0"" xmlns:edmx=""http://docs.oasis-open.org/odata/ns/edmx"">
  <edmx:DataServices>
    <Schema Namespace=""Affra.Service.View.Domain.Views"" xmlns=""http://docs.oasis-open.org/odata/ns/edm"">
      <EntityType Name=""View"">
        <Key>
          <PropertyRef Name=""Id"" />
        </Key>
        <Property Name=""Id"" Type=""Edm.Int64"" Nullable=""false"" />
        <Property Name=""Name"" Type=""Edm.String"" Nullable=""false"" />
        <Property Name=""xmin"" Type=""Edm.Int64"" Nullable=""false"" />
        <NavigationProperty Name=""Rows"" Type=""Collection(Affra.Service.View.Domain.Views.Row)"" />
      </EntityType>
      <EntityType Name=""Row"">
        <Key>
          <PropertyRef Name=""Id"" />
        </Key>
        <Property Name=""Id"" Type=""Edm.Int64"" Nullable=""false"" />
        <Property Name=""Sequence"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""ViewName"" Type=""Edm.String"" Nullable=""false"" />
        <Property Name=""xmin"" Type=""Edm.Int64"" Nullable=""false"" />
        <NavigationProperty Name=""View"" Type=""Affra.Service.View.Domain.Views.View"" />
        <NavigationProperty Name=""Columns"" Type=""Collection(Affra.Service.View.Domain.Views.Column)"" />
      </EntityType>
      <EntityType Name=""Column"">
        <Key>
          <PropertyRef Name=""Id"" />
        </Key>
        <Property Name=""Id"" Type=""Edm.Int64"" Nullable=""false"" />
        <Property Name=""Sequence"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""RowId"" Type=""Edm.Int64"" />
        <Property Name=""ComponentType"" Type=""Edm.String"" />
        <Property Name=""ColumnComponent"" Type=""Edm.String"" />
        <Property Name=""ViewName"" Type=""Edm.String"" Nullable=""false"" />
        <Property Name=""xmin"" Type=""Edm.Int64"" Nullable=""false"" />
        <NavigationProperty Name=""Row"" Type=""Affra.Service.View.Domain.Views.Row"">
          <ReferentialConstraint Property=""RowId"" ReferencedProperty=""Id"" />
        </NavigationProperty>
        <NavigationProperty Name=""View"" Type=""Affra.Service.View.Domain.Views.View"" />
      </EntityType>
    </Schema>
    <Schema Namespace=""Default"" xmlns=""http://docs.oasis-open.org/odata/ns/edm"">
      <EntityContainer Name=""Container"">
        <EntitySet Name=""View"" EntityType=""Affra.Service.View.Domain.Views.View"">
          <NavigationPropertyBinding Path=""Rows"" Target=""Row"" />
          <Annotation Term=""Org.OData.Core.V1.OptimisticConcurrency"">
            <Collection>
              <PropertyPath>xmin</PropertyPath>
            </Collection>
          </Annotation>
        </EntitySet>
        <EntitySet Name=""Row"" EntityType=""Affra.Service.View.Domain.Views.Row"">
          <NavigationPropertyBinding Path=""Columns"" Target=""Column"" />
          <NavigationPropertyBinding Path=""View"" Target=""View"" />
          <Annotation Term=""Org.OData.Core.V1.OptimisticConcurrency"">
            <Collection>
              <PropertyPath>xmin</PropertyPath>
            </Collection>
          </Annotation>
        </EntitySet>
        <EntitySet Name=""Column"" EntityType=""Affra.Service.View.Domain.Views.Column"">
          <NavigationPropertyBinding Path=""Row"" Target=""Row"" />
          <NavigationPropertyBinding Path=""View"" Target=""View"" />
          <Annotation Term=""Org.OData.Core.V1.OptimisticConcurrency"">
            <Collection>
              <PropertyPath>xmin</PropertyPath>
            </Collection>
          </Annotation>
        </EntitySet>
      </EntityContainer>
    </Schema>
  </edmx:DataServices>
</edmx:Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
            public static global::Microsoft.OData.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
            private static global::Microsoft.OData.Edm.IEdmModel LoadModelFromString()
            {
                global::System.Xml.XmlReader reader = CreateXmlReader(Edmx);
                try
                {
                    global::System.Collections.Generic.IEnumerable<global::Microsoft.OData.Edm.Validation.EdmError> errors;
                    global::Microsoft.OData.Edm.IEdmModel edmModel;
                    
                    if (!global::Microsoft.OData.Edm.Csdl.CsdlReader.TryParse(reader, false, out edmModel, out errors))
                    {
                        global::System.Text.StringBuilder errorMessages = new global::System.Text.StringBuilder();
                        foreach (var error in errors)
                        {
                            errorMessages.Append(error.ErrorMessage);
                            errorMessages.Append("; ");
                        }
                        throw new global::System.InvalidOperationException(errorMessages.ToString());
                    }

                    return edmModel;
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
    }
}
