//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 17/4/2022 12:41:01 PM
namespace DataExtractorODataService.Affra.Service.DataExtractor.Domain.Accounts
{
    /// <summary>
    /// There are no comments for AccountSingle in the schema.
    /// </summary>
    public partial class AccountSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Account>
    {
        /// <summary>
        /// Initialize a new AccountSingle object.
        /// </summary>
        public AccountSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new AccountSingle object.
        /// </summary>
        public AccountSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new AccountSingle object.
        /// </summary>
        public AccountSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<Account> query)
            : base(query) {}

    }
    /// <summary>
    /// There are no comments for Account in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Id")]
    public partial class Account : global::Microsoft.OData.Client.BaseEntityType
    {
        /// <summary>
        /// Create a new Account object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="xmin">Initial value of xmin.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        public static Account CreateAccount(string ID, long xmin)
        {
            Account account = new Account();
            account.Id = ID;
            account.xmin = xmin;
            return account;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        public string Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        private string _Id;
        partial void OnIdChanging(string value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property xmin in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        public long xmin
        {
            get
            {
                return this._xmin;
            }
            set
            {
                this.OnxminChanging(value);
                this._xmin = value;
                this.OnxminChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        private long _xmin;
        partial void OnxminChanging(long value);
        partial void OnxminChanged();
    }
    /// <summary>
    /// Class containing all extension methods
    /// </summary>
    public static class ExtensionMethods
    {
        /// <summary>
        /// Get an entity of type global::DataExtractorODataService.Affra.Service.DataExtractor.Domain.Accounts.Account as global::DataExtractorODataService.Affra.Service.DataExtractor.Domain.Accounts.AccountSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::DataExtractorODataService.Affra.Service.DataExtractor.Domain.Accounts.AccountSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::DataExtractorODataService.Affra.Service.DataExtractor.Domain.Accounts.Account> _source, global::System.Collections.Generic.IDictionary<string, object> keys)
        {
            return new global::DataExtractorODataService.Affra.Service.DataExtractor.Domain.Accounts.AccountSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::DataExtractorODataService.Affra.Service.DataExtractor.Domain.Accounts.Account as global::DataExtractorODataService.Affra.Service.DataExtractor.Domain.Accounts.AccountSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="id">The value of id</param>
        public static global::DataExtractorODataService.Affra.Service.DataExtractor.Domain.Accounts.AccountSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::DataExtractorODataService.Affra.Service.DataExtractor.Domain.Accounts.Account> _source,
            string id)
        {
            global::System.Collections.Generic.IDictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "Id", id }
            };
            return new global::DataExtractorODataService.Affra.Service.DataExtractor.Domain.Accounts.AccountSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, keys)));
        }
    }
}
namespace DataExtractorODataService.Affra.Service.DataExtractor.Domain.Files
{
    /// <summary>
    /// There are no comments for FileSingle in the schema.
    /// </summary>
    public partial class FileSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<File>
    {
        /// <summary>
        /// Initialize a new FileSingle object.
        /// </summary>
        public FileSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new FileSingle object.
        /// </summary>
        public FileSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new FileSingle object.
        /// </summary>
        public FileSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<File> query)
            : base(query) {}

    }
    /// <summary>
    /// There are no comments for File in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Id")]
    public partial class File : global::Microsoft.OData.Client.BaseEntityType
    {
        /// <summary>
        /// Create a new File object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="lastUpdatedDateTime">Initial value of LastUpdatedDateTime.</param>
        /// <param name="pickupDateTime">Initial value of PickupDateTime.</param>
        /// <param name="processStatus">Initial value of ProcessStatus.</param>
        /// <param name="numberOfAttempts">Initial value of NumberOfAttempts.</param>
        /// <param name="xmin">Initial value of xmin.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        public static File CreateFile(long ID, 
                    global::System.DateTimeOffset lastUpdatedDateTime, 
                    global::System.DateTimeOffset pickupDateTime, 
                    global::DataExtractorODataService.Affra.Service.DataExtractor.Domain.Files.FileProcessStatus processStatus, 
                    int numberOfAttempts, 
                    long xmin)
        {
            File file = new File();
            file.Id = ID;
            file.LastUpdatedDateTime = lastUpdatedDateTime;
            file.PickupDateTime = pickupDateTime;
            file.ProcessStatus = processStatus;
            file.NumberOfAttempts = numberOfAttempts;
            file.xmin = xmin;
            return file;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        public long Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        private long _Id;
        partial void OnIdChanging(long value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property FolderName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        public string FolderName
        {
            get
            {
                return this._FolderName;
            }
            set
            {
                this.OnFolderNameChanging(value);
                this._FolderName = value;
                this.OnFolderNameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        private string _FolderName;
        partial void OnFolderNameChanging(string value);
        partial void OnFolderNameChanged();
        /// <summary>
        /// There are no comments for Property FileName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        public string FileName
        {
            get
            {
                return this._FileName;
            }
            set
            {
                this.OnFileNameChanging(value);
                this._FileName = value;
                this.OnFileNameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        private string _FileName;
        partial void OnFileNameChanging(string value);
        partial void OnFileNameChanged();
        /// <summary>
        /// There are no comments for Property LastUpdatedDateTime in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        public global::System.DateTimeOffset LastUpdatedDateTime
        {
            get
            {
                return this._LastUpdatedDateTime;
            }
            set
            {
                this.OnLastUpdatedDateTimeChanging(value);
                this._LastUpdatedDateTime = value;
                this.OnLastUpdatedDateTimeChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        private global::System.DateTimeOffset _LastUpdatedDateTime;
        partial void OnLastUpdatedDateTimeChanging(global::System.DateTimeOffset value);
        partial void OnLastUpdatedDateTimeChanged();
        /// <summary>
        /// There are no comments for Property PickupDateTime in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        public global::System.DateTimeOffset PickupDateTime
        {
            get
            {
                return this._PickupDateTime;
            }
            set
            {
                this.OnPickupDateTimeChanging(value);
                this._PickupDateTime = value;
                this.OnPickupDateTimeChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        private global::System.DateTimeOffset _PickupDateTime;
        partial void OnPickupDateTimeChanging(global::System.DateTimeOffset value);
        partial void OnPickupDateTimeChanged();
        /// <summary>
        /// There are no comments for Property ProcessStatus in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        public global::DataExtractorODataService.Affra.Service.DataExtractor.Domain.Files.FileProcessStatus ProcessStatus
        {
            get
            {
                return this._ProcessStatus;
            }
            set
            {
                this.OnProcessStatusChanging(value);
                this._ProcessStatus = value;
                this.OnProcessStatusChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        private global::DataExtractorODataService.Affra.Service.DataExtractor.Domain.Files.FileProcessStatus _ProcessStatus;
        partial void OnProcessStatusChanging(global::DataExtractorODataService.Affra.Service.DataExtractor.Domain.Files.FileProcessStatus value);
        partial void OnProcessStatusChanged();
        /// <summary>
        /// There are no comments for Property NumberOfAttempts in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        public int NumberOfAttempts
        {
            get
            {
                return this._NumberOfAttempts;
            }
            set
            {
                this.OnNumberOfAttemptsChanging(value);
                this._NumberOfAttempts = value;
                this.OnNumberOfAttemptsChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        private int _NumberOfAttempts;
        partial void OnNumberOfAttemptsChanging(int value);
        partial void OnNumberOfAttemptsChanged();
        /// <summary>
        /// There are no comments for Property xmin in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        public long xmin
        {
            get
            {
                return this._xmin;
            }
            set
            {
                this.OnxminChanging(value);
                this._xmin = value;
                this.OnxminChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        private long _xmin;
        partial void OnxminChanging(long value);
        partial void OnxminChanged();
    }
    /// <summary>
    /// There are no comments for FileProcessStatus in the schema.
    /// </summary>
    public enum FileProcessStatus
    {
        Processing = 0,
        Failed = 1,
        Completed = 2
    }
    /// <summary>
    /// Class containing all extension methods
    /// </summary>
    public static class ExtensionMethods
    {
        /// <summary>
        /// Get an entity of type global::DataExtractorODataService.Affra.Service.DataExtractor.Domain.Files.File as global::DataExtractorODataService.Affra.Service.DataExtractor.Domain.Files.FileSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::DataExtractorODataService.Affra.Service.DataExtractor.Domain.Files.FileSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::DataExtractorODataService.Affra.Service.DataExtractor.Domain.Files.File> _source, global::System.Collections.Generic.IDictionary<string, object> keys)
        {
            return new global::DataExtractorODataService.Affra.Service.DataExtractor.Domain.Files.FileSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::DataExtractorODataService.Affra.Service.DataExtractor.Domain.Files.File as global::DataExtractorODataService.Affra.Service.DataExtractor.Domain.Files.FileSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="id">The value of id</param>
        public static global::DataExtractorODataService.Affra.Service.DataExtractor.Domain.Files.FileSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::DataExtractorODataService.Affra.Service.DataExtractor.Domain.Files.File> _source,
            long id)
        {
            global::System.Collections.Generic.IDictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "Id", id }
            };
            return new global::DataExtractorODataService.Affra.Service.DataExtractor.Domain.Files.FileSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, keys)));
        }
    }
}
namespace DataExtractorODataService.Default
{
    /// <summary>
    /// There are no comments for Container in the schema.
    /// </summary>
    public partial class Container : global::Microsoft.OData.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new Container object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        public Container(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::Microsoft.OData.Client.ODataProtocolVersion.V4)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
            this.Format.UseJson();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "Affra.Service.DataExtractor.Domain.Accounts", "DataExtractorODataService.Affra.Service.DataExtractor.Domain.Accounts");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            resolvedType = this.DefaultResolveType(typeName, "Affra.Service.DataExtractor.Domain.Files", "DataExtractorODataService.Affra.Service.DataExtractor.Domain.Files");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            resolvedType = this.DefaultResolveType(typeName, "Default", "DataExtractorODataService.Default");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("DataExtractorODataService.Affra.Service.DataExtractor.Domain.Accounts", global::System.StringComparison.Ordinal))
            {
                return string.Concat("Affra.Service.DataExtractor.Domain.Accounts.", clientType.Name);
            }
            if (clientType.Namespace.Equals("DataExtractorODataService.Affra.Service.DataExtractor.Domain.Files", global::System.StringComparison.Ordinal))
            {
                return string.Concat("Affra.Service.DataExtractor.Domain.Files.", clientType.Name);
            }
            if (clientType.Namespace.Equals("DataExtractorODataService.Default", global::System.StringComparison.Ordinal))
            {
                return string.Concat("Default.", clientType.Name);
            }
            return clientType.FullName;
        }
        /// <summary>
        /// There are no comments for Account in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::DataExtractorODataService.Affra.Service.DataExtractor.Domain.Accounts.Account> Account
        {
            get
            {
                if ((this._Account == null))
                {
                    this._Account = base.CreateQuery<global::DataExtractorODataService.Affra.Service.DataExtractor.Domain.Accounts.Account>("Account");
                }
                return this._Account;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::DataExtractorODataService.Affra.Service.DataExtractor.Domain.Accounts.Account> _Account;
        /// <summary>
        /// There are no comments for File in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::DataExtractorODataService.Affra.Service.DataExtractor.Domain.Files.File> File
        {
            get
            {
                if ((this._File == null))
                {
                    this._File = base.CreateQuery<global::DataExtractorODataService.Affra.Service.DataExtractor.Domain.Files.File>("File");
                }
                return this._File;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::DataExtractorODataService.Affra.Service.DataExtractor.Domain.Files.File> _File;
        /// <summary>
        /// There are no comments for Account in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        public void AddToAccount(global::DataExtractorODataService.Affra.Service.DataExtractor.Domain.Accounts.Account account)
        {
            base.AddObject("Account", account);
        }
        /// <summary>
        /// There are no comments for File in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        public void AddToFile(global::DataExtractorODataService.Affra.Service.DataExtractor.Domain.Files.File file)
        {
            base.AddObject("File", file);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
            private static global::Microsoft.OData.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
            private const string Edmx = @"<edmx:Edmx Version=""4.0"" xmlns:edmx=""http://docs.oasis-open.org/odata/ns/edmx"">
  <edmx:DataServices>
    <Schema Namespace=""Affra.Service.DataExtractor.Domain.Accounts"" xmlns=""http://docs.oasis-open.org/odata/ns/edm"">
      <EntityType Name=""Account"">
        <Key>
          <PropertyRef Name=""Id"" />
        </Key>
        <Property Name=""Id"" Type=""Edm.String"" Nullable=""false"" />
        <Property Name=""Name"" Type=""Edm.String"" />
        <Property Name=""xmin"" Type=""Edm.Int64"" Nullable=""false"" />
      </EntityType>
    </Schema>
    <Schema Namespace=""Affra.Service.DataExtractor.Domain.Files"" xmlns=""http://docs.oasis-open.org/odata/ns/edm"">
      <EntityType Name=""File"">
        <Key>
          <PropertyRef Name=""Id"" />
        </Key>
        <Property Name=""Id"" Type=""Edm.Int64"" Nullable=""false"" />
        <Property Name=""FolderName"" Type=""Edm.String"" />
        <Property Name=""FileName"" Type=""Edm.String"" />
        <Property Name=""LastUpdatedDateTime"" Type=""Edm.DateTimeOffset"" Nullable=""false"" />
        <Property Name=""PickupDateTime"" Type=""Edm.DateTimeOffset"" Nullable=""false"" />
        <Property Name=""ProcessStatus"" Type=""Affra.Service.DataExtractor.Domain.Files.FileProcessStatus"" Nullable=""false"" />
        <Property Name=""NumberOfAttempts"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""xmin"" Type=""Edm.Int64"" Nullable=""false"" />
      </EntityType>
      <EnumType Name=""FileProcessStatus"">
        <Member Name=""Processing"" Value=""0"" />
        <Member Name=""Failed"" Value=""1"" />
        <Member Name=""Completed"" Value=""2"" />
      </EnumType>
    </Schema>
    <Schema Namespace=""Default"" xmlns=""http://docs.oasis-open.org/odata/ns/edm"">
      <EntityContainer Name=""Container"">
        <EntitySet Name=""Account"" EntityType=""Affra.Service.DataExtractor.Domain.Accounts.Account"">
          <Annotation Term=""Org.OData.Core.V1.OptimisticConcurrency"">
            <Collection>
              <PropertyPath>xmin</PropertyPath>
            </Collection>
          </Annotation>
        </EntitySet>
        <EntitySet Name=""File"" EntityType=""Affra.Service.DataExtractor.Domain.Files.File"">
          <Annotation Term=""Org.OData.Core.V1.OptimisticConcurrency"">
            <Collection>
              <PropertyPath>xmin</PropertyPath>
            </Collection>
          </Annotation>
        </EntitySet>
      </EntityContainer>
    </Schema>
  </edmx:DataServices>
</edmx:Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
            public static global::Microsoft.OData.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
            private static global::Microsoft.OData.Edm.IEdmModel LoadModelFromString()
            {
                global::System.Xml.XmlReader reader = CreateXmlReader(Edmx);
                try
                {
                    global::System.Collections.Generic.IEnumerable<global::Microsoft.OData.Edm.Validation.EdmError> errors;
                    global::Microsoft.OData.Edm.IEdmModel edmModel;
                    
                    if (!global::Microsoft.OData.Edm.Csdl.CsdlReader.TryParse(reader, false, out edmModel, out errors))
                    {
                        global::System.Text.StringBuilder errorMessages = new global::System.Text.StringBuilder();
                        foreach (var error in errors)
                        {
                            errorMessages.Append(error.ErrorMessage);
                            errorMessages.Append("; ");
                        }
                        throw new global::System.InvalidOperationException(errorMessages.ToString());
                    }

                    return edmModel;
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
    }
}
