namespace JXNippon.CentralizedDatabaseSystem.Shared.Description
{
    public enum ImageFile
    {
        AcceptTasks,
        AllApproved,
        CalendarAnalysis,
        ColumnConfig,
        Completed,
        CompleteLogin,
        DataExtraction,
        DatePicker,
        Departing,
        Designer,
        ErrorForbidden,
        ErrorNotFound,
        Gauge,
        LowBattery,
        Merger,
        NewTasks,
        NoData,
        Piechart,
        RangePicker,
        Research,
        Search,
        Stats,
        Steps,
        Tasks,
        Teleport,
        TodoList,
        WorkInProgress,
    }
}
