//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 30/4/2022 4:16:52 PM
namespace DataExtractorODataService.Affra.Service.DataExtractor.Domain.DataFiles
{
    /// <summary>
    /// There are no comments for DataFileSingle in the schema.
    /// </summary>
    public partial class DataFileSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<DataFile>
    {
        /// <summary>
        /// Initialize a new DataFileSingle object.
        /// </summary>
        public DataFileSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new DataFileSingle object.
        /// </summary>
        public DataFileSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new DataFileSingle object.
        /// </summary>
        public DataFileSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<DataFile> query)
            : base(query) {}

    }
    /// <summary>
    /// There are no comments for DataFile in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Id")]
    public partial class DataFile : global::Microsoft.OData.Client.BaseEntityType
    {
        /// <summary>
        /// Create a new DataFile object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="lastModifiedDateTime">Initial value of LastModifiedDateTime.</param>
        /// <param name="processStatus">Initial value of ProcessStatus.</param>
        /// <param name="numberOfAttempts">Initial value of NumberOfAttempts.</param>
        /// <param name="xmin">Initial value of xmin.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        public static DataFile CreateDataFile(long ID, global::System.DateTimeOffset lastModifiedDateTime, global::DataExtractorODataService.Affra.Service.DataExtractor.Domain.DataFiles.FileProcessStatus processStatus, int numberOfAttempts, long xmin)
        {
            DataFile dataFile = new DataFile();
            dataFile.Id = ID;
            dataFile.LastModifiedDateTime = lastModifiedDateTime;
            dataFile.ProcessStatus = processStatus;
            dataFile.NumberOfAttempts = numberOfAttempts;
            dataFile.xmin = xmin;
            return dataFile;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        public long Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        private long _Id;
        partial void OnIdChanging(long value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property FolderName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        public string FolderName
        {
            get
            {
                return this._FolderName;
            }
            set
            {
                this.OnFolderNameChanging(value);
                this._FolderName = value;
                this.OnFolderNameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        private string _FolderName;
        partial void OnFolderNameChanging(string value);
        partial void OnFolderNameChanged();
        /// <summary>
        /// There are no comments for Property FileName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        public string FileName
        {
            get
            {
                return this._FileName;
            }
            set
            {
                this.OnFileNameChanging(value);
                this._FileName = value;
                this.OnFileNameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        private string _FileName;
        partial void OnFileNameChanging(string value);
        partial void OnFileNameChanged();
        /// <summary>
        /// There are no comments for Property LastModifiedDateTime in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        public global::System.DateTimeOffset LastModifiedDateTime
        {
            get
            {
                return this._LastModifiedDateTime;
            }
            set
            {
                this.OnLastModifiedDateTimeChanging(value);
                this._LastModifiedDateTime = value;
                this.OnLastModifiedDateTimeChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        private global::System.DateTimeOffset _LastModifiedDateTime;
        partial void OnLastModifiedDateTimeChanging(global::System.DateTimeOffset value);
        partial void OnLastModifiedDateTimeChanged();
        /// <summary>
        /// There are no comments for Property JobStartDateTime in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        public global::System.Nullable<global::System.DateTimeOffset> JobStartDateTime
        {
            get
            {
                return this._JobStartDateTime;
            }
            set
            {
                this.OnJobStartDateTimeChanging(value);
                this._JobStartDateTime = value;
                this.OnJobStartDateTimeChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        private global::System.Nullable<global::System.DateTimeOffset> _JobStartDateTime;
        partial void OnJobStartDateTimeChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnJobStartDateTimeChanged();
        /// <summary>
        /// There are no comments for Property ProcessedLastModifiedDateTime in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        public global::System.Nullable<global::System.DateTimeOffset> ProcessedLastModifiedDateTime
        {
            get
            {
                return this._ProcessedLastModifiedDateTime;
            }
            set
            {
                this.OnProcessedLastModifiedDateTimeChanging(value);
                this._ProcessedLastModifiedDateTime = value;
                this.OnProcessedLastModifiedDateTimeChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        private global::System.Nullable<global::System.DateTimeOffset> _ProcessedLastModifiedDateTime;
        partial void OnProcessedLastModifiedDateTimeChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnProcessedLastModifiedDateTimeChanged();
        /// <summary>
        /// There are no comments for Property ProcessStatus in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        public global::DataExtractorODataService.Affra.Service.DataExtractor.Domain.DataFiles.FileProcessStatus ProcessStatus
        {
            get
            {
                return this._ProcessStatus;
            }
            set
            {
                this.OnProcessStatusChanging(value);
                this._ProcessStatus = value;
                this.OnProcessStatusChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        private global::DataExtractorODataService.Affra.Service.DataExtractor.Domain.DataFiles.FileProcessStatus _ProcessStatus;
        partial void OnProcessStatusChanging(global::DataExtractorODataService.Affra.Service.DataExtractor.Domain.DataFiles.FileProcessStatus value);
        partial void OnProcessStatusChanged();
        /// <summary>
        /// There are no comments for Property NumberOfAttempts in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        public int NumberOfAttempts
        {
            get
            {
                return this._NumberOfAttempts;
            }
            set
            {
                this.OnNumberOfAttemptsChanging(value);
                this._NumberOfAttempts = value;
                this.OnNumberOfAttemptsChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        private int _NumberOfAttempts;
        partial void OnNumberOfAttemptsChanging(int value);
        partial void OnNumberOfAttemptsChanged();
        /// <summary>
        /// There are no comments for Property xmin in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        public long xmin
        {
            get
            {
                return this._xmin;
            }
            set
            {
                this.OnxminChanging(value);
                this._xmin = value;
                this.OnxminChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        private long _xmin;
        partial void OnxminChanging(long value);
        partial void OnxminChanged();
    }
    /// <summary>
    /// There are no comments for FileProcessStatus in the schema.
    /// </summary>
    public enum FileProcessStatus
    {
        Pending = 0,
        Processing = 1,
        Failed = 2,
        Completed = 3
    }
    /// <summary>
    /// Class containing all extension methods
    /// </summary>
    public static class ExtensionMethods
    {
        /// <summary>
        /// Get an entity of type global::DataExtractorODataService.Affra.Service.DataExtractor.Domain.DataFiles.DataFile as global::DataExtractorODataService.Affra.Service.DataExtractor.Domain.DataFiles.DataFileSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::DataExtractorODataService.Affra.Service.DataExtractor.Domain.DataFiles.DataFileSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::DataExtractorODataService.Affra.Service.DataExtractor.Domain.DataFiles.DataFile> _source, global::System.Collections.Generic.IDictionary<string, object> keys)
        {
            return new global::DataExtractorODataService.Affra.Service.DataExtractor.Domain.DataFiles.DataFileSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::DataExtractorODataService.Affra.Service.DataExtractor.Domain.DataFiles.DataFile as global::DataExtractorODataService.Affra.Service.DataExtractor.Domain.DataFiles.DataFileSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="id">The value of id</param>
        public static global::DataExtractorODataService.Affra.Service.DataExtractor.Domain.DataFiles.DataFileSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::DataExtractorODataService.Affra.Service.DataExtractor.Domain.DataFiles.DataFile> _source,
            long id)
        {
            global::System.Collections.Generic.IDictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "Id", id }
            };
            return new global::DataExtractorODataService.Affra.Service.DataExtractor.Domain.DataFiles.DataFileSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, keys)));
        }
    }
}
namespace DataExtractorODataService.Default
{
    /// <summary>
    /// There are no comments for Container in the schema.
    /// </summary>
    public partial class Container : global::Microsoft.OData.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new Container object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        public Container(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::Microsoft.OData.Client.ODataProtocolVersion.V4)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
            this.Format.UseJson();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "Affra.Service.DataExtractor.Domain.DataFiles", "DataExtractorODataService.Affra.Service.DataExtractor.Domain.DataFiles");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            resolvedType = this.DefaultResolveType(typeName, "Default", "DataExtractorODataService.Default");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("DataExtractorODataService.Affra.Service.DataExtractor.Domain.DataFiles", global::System.StringComparison.Ordinal))
            {
                return string.Concat("Affra.Service.DataExtractor.Domain.DataFiles.", clientType.Name);
            }
            if (clientType.Namespace.Equals("DataExtractorODataService.Default", global::System.StringComparison.Ordinal))
            {
                return string.Concat("Default.", clientType.Name);
            }
            return clientType.FullName;
        }
        /// <summary>
        /// There are no comments for DataFile in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::DataExtractorODataService.Affra.Service.DataExtractor.Domain.DataFiles.DataFile> DataFile
        {
            get
            {
                if ((this._DataFile == null))
                {
                    this._DataFile = base.CreateQuery<global::DataExtractorODataService.Affra.Service.DataExtractor.Domain.DataFiles.DataFile>("DataFile");
                }
                return this._DataFile;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::DataExtractorODataService.Affra.Service.DataExtractor.Domain.DataFiles.DataFile> _DataFile;
        /// <summary>
        /// There are no comments for DataFile in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        public void AddToDataFile(global::DataExtractorODataService.Affra.Service.DataExtractor.Domain.DataFiles.DataFile dataFile)
        {
            base.AddObject("DataFile", dataFile);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
            private static global::Microsoft.OData.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
            private const string Edmx = @"<edmx:Edmx Version=""4.0"" xmlns:edmx=""http://docs.oasis-open.org/odata/ns/edmx"">
  <edmx:DataServices>
    <Schema Namespace=""Affra.Service.DataExtractor.Domain.DataFiles"" xmlns=""http://docs.oasis-open.org/odata/ns/edm"">
      <EntityType Name=""DataFile"">
        <Key>
          <PropertyRef Name=""Id"" />
        </Key>
        <Property Name=""Id"" Type=""Edm.Int64"" Nullable=""false"" />
        <Property Name=""FolderName"" Type=""Edm.String"" />
        <Property Name=""FileName"" Type=""Edm.String"" />
        <Property Name=""LastModifiedDateTime"" Type=""Edm.DateTimeOffset"" Nullable=""false"" />
        <Property Name=""JobStartDateTime"" Type=""Edm.DateTimeOffset"" />
        <Property Name=""ProcessedLastModifiedDateTime"" Type=""Edm.DateTimeOffset"" />
        <Property Name=""ProcessStatus"" Type=""Affra.Service.DataExtractor.Domain.DataFiles.FileProcessStatus"" Nullable=""false"" />
        <Property Name=""NumberOfAttempts"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""xmin"" Type=""Edm.Int64"" Nullable=""false"" />
      </EntityType>
      <EnumType Name=""FileProcessStatus"">
        <Member Name=""Pending"" Value=""0"" />
        <Member Name=""Processing"" Value=""1"" />
        <Member Name=""Failed"" Value=""2"" />
        <Member Name=""Completed"" Value=""3"" />
      </EnumType>
    </Schema>
    <Schema Namespace=""Default"" xmlns=""http://docs.oasis-open.org/odata/ns/edm"">
      <EntityContainer Name=""Container"">
        <EntitySet Name=""DataFile"" EntityType=""Affra.Service.DataExtractor.Domain.DataFiles.DataFile"">
          <Annotation Term=""Org.OData.Core.V1.OptimisticConcurrency"">
            <Collection>
              <PropertyPath>xmin</PropertyPath>
            </Collection>
          </Annotation>
        </EntitySet>
      </EntityContainer>
    </Schema>
  </edmx:DataServices>
</edmx:Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
            public static global::Microsoft.OData.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
            private static global::Microsoft.OData.Edm.IEdmModel LoadModelFromString()
            {
                global::System.Xml.XmlReader reader = CreateXmlReader(Edmx);
                try
                {
                    global::System.Collections.Generic.IEnumerable<global::Microsoft.OData.Edm.Validation.EdmError> errors;
                    global::Microsoft.OData.Edm.IEdmModel edmModel;
                    
                    if (!global::Microsoft.OData.Edm.Csdl.CsdlReader.TryParse(reader, false, out edmModel, out errors))
                    {
                        global::System.Text.StringBuilder errorMessages = new global::System.Text.StringBuilder();
                        foreach (var error in errors)
                        {
                            errorMessages.Append(error.ErrorMessage);
                            errorMessages.Append("; ");
                        }
                        throw new global::System.InvalidOperationException(errorMessages.ToString());
                    }

                    return edmModel;
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
    }
}
