//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 2/8/2022 11:50:42 AM
namespace NotificationODataService.Affra.Service.Notification.Domain.PersonalMessages
{
    /// <summary>
    /// There are no comments for MessageSingle in the schema.
    /// </summary>
    public partial class MessageSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Message>
    {
        /// <summary>
        /// Initialize a new MessageSingle object.
        /// </summary>
        public MessageSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new MessageSingle object.
        /// </summary>
        public MessageSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new MessageSingle object.
        /// </summary>
        public MessageSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<Message> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for PersonalMessages in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::NotificationODataService.Affra.Service.Notification.Domain.PersonalMessages.PersonalMessage> PersonalMessages
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._PersonalMessages == null))
                {
                    this._PersonalMessages = Context.CreateQuery<global::NotificationODataService.Affra.Service.Notification.Domain.PersonalMessages.PersonalMessage>(GetPath("PersonalMessages"));
                }
                return this._PersonalMessages;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::NotificationODataService.Affra.Service.Notification.Domain.PersonalMessages.PersonalMessage> _PersonalMessages;
    }
    /// <summary>
    /// There are no comments for Message in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Id")]
    public partial class Message : global::Microsoft.OData.Client.BaseEntityType
    {
        /// <summary>
        /// Create a new Message object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="createdDateTime">Initial value of CreatedDateTime.</param>
        /// <param name="xmin">Initial value of xmin.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        public static Message CreateMessage(global::System.Guid ID, global::System.DateTimeOffset createdDateTime, long xmin)
        {
            Message message = new Message();
            message.Id = ID;
            message.CreatedDateTime = createdDateTime;
            message.xmin = xmin;
            return message;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        public global::System.Guid Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Subject in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        public string Subject
        {
            get
            {
                return this._Subject;
            }
            set
            {
                this.OnSubjectChanging(value);
                this._Subject = value;
                this.OnSubjectChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        private string _Subject;
        partial void OnSubjectChanging(string value);
        partial void OnSubjectChanged();
        /// <summary>
        /// There are no comments for Property Content in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        public string Content
        {
            get
            {
                return this._Content;
            }
            set
            {
                this.OnContentChanging(value);
                this._Content = value;
                this.OnContentChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        private string _Content;
        partial void OnContentChanging(string value);
        partial void OnContentChanged();
        /// <summary>
        /// There are no comments for Property Extra in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        public string Extra
        {
            get
            {
                return this._Extra;
            }
            set
            {
                this.OnExtraChanging(value);
                this._Extra = value;
                this.OnExtraChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        private string _Extra;
        partial void OnExtraChanging(string value);
        partial void OnExtraChanged();
        /// <summary>
        /// There are no comments for Property CreatedDateTime in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        public global::System.DateTimeOffset CreatedDateTime
        {
            get
            {
                return this._CreatedDateTime;
            }
            set
            {
                this.OnCreatedDateTimeChanging(value);
                this._CreatedDateTime = value;
                this.OnCreatedDateTimeChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        private global::System.DateTimeOffset _CreatedDateTime;
        partial void OnCreatedDateTimeChanging(global::System.DateTimeOffset value);
        partial void OnCreatedDateTimeChanged();
        /// <summary>
        /// There are no comments for Property CreatedBy in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        public string CreatedBy
        {
            get
            {
                return this._CreatedBy;
            }
            set
            {
                this.OnCreatedByChanging(value);
                this._CreatedBy = value;
                this.OnCreatedByChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        private string _CreatedBy;
        partial void OnCreatedByChanging(string value);
        partial void OnCreatedByChanged();
        /// <summary>
        /// There are no comments for Property xmin in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        public long xmin
        {
            get
            {
                return this._xmin;
            }
            set
            {
                this.OnxminChanging(value);
                this._xmin = value;
                this.OnxminChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        private long _xmin;
        partial void OnxminChanging(long value);
        partial void OnxminChanged();
        /// <summary>
        /// There are no comments for Property PersonalMessages in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        public global::System.Collections.ObjectModel.Collection<global::NotificationODataService.Affra.Service.Notification.Domain.PersonalMessages.PersonalMessage> PersonalMessages
        {
            get
            {
                return this._PersonalMessages;
            }
            set
            {
                this.OnPersonalMessagesChanging(value);
                this._PersonalMessages = value;
                this.OnPersonalMessagesChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        private global::System.Collections.ObjectModel.Collection<global::NotificationODataService.Affra.Service.Notification.Domain.PersonalMessages.PersonalMessage> _PersonalMessages = new global::System.Collections.ObjectModel.Collection<global::NotificationODataService.Affra.Service.Notification.Domain.PersonalMessages.PersonalMessage>();
        partial void OnPersonalMessagesChanging(global::System.Collections.ObjectModel.Collection<global::NotificationODataService.Affra.Service.Notification.Domain.PersonalMessages.PersonalMessage> value);
        partial void OnPersonalMessagesChanged();
    }
    /// <summary>
    /// There are no comments for PersonalMessageSingle in the schema.
    /// </summary>
    public partial class PersonalMessageSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<PersonalMessage>
    {
        /// <summary>
        /// Initialize a new PersonalMessageSingle object.
        /// </summary>
        public PersonalMessageSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new PersonalMessageSingle object.
        /// </summary>
        public PersonalMessageSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new PersonalMessageSingle object.
        /// </summary>
        public PersonalMessageSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<PersonalMessage> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for Message in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        public global::NotificationODataService.Affra.Service.Notification.Domain.PersonalMessages.MessageSingle Message
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Message == null))
                {
                    this._Message = new global::NotificationODataService.Affra.Service.Notification.Domain.PersonalMessages.MessageSingle(this.Context, GetPath("Message"));
                }
                return this._Message;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        private global::NotificationODataService.Affra.Service.Notification.Domain.PersonalMessages.MessageSingle _Message;
    }
    /// <summary>
    /// There are no comments for PersonalMessage in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Id")]
    public partial class PersonalMessage : global::Microsoft.OData.Client.BaseEntityType
    {
        /// <summary>
        /// Create a new PersonalMessage object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="createdDateTime">Initial value of CreatedDateTime.</param>
        /// <param name="status">Initial value of Status.</param>
        /// <param name="xmin">Initial value of xmin.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        public static PersonalMessage CreatePersonalMessage(global::System.Guid ID, global::System.DateTimeOffset createdDateTime, global::NotificationODataService.Affra.Service.Notification.Domain.PersonalMessages.PersonalMessageStatus status, long xmin)
        {
            PersonalMessage personalMessage = new PersonalMessage();
            personalMessage.Id = ID;
            personalMessage.CreatedDateTime = createdDateTime;
            personalMessage.Status = status;
            personalMessage.xmin = xmin;
            return personalMessage;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        public global::System.Guid Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property MessageId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        public global::System.Nullable<global::System.Guid> MessageId
        {
            get
            {
                return this._MessageId;
            }
            set
            {
                this.OnMessageIdChanging(value);
                this._MessageId = value;
                this.OnMessageIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        private global::System.Nullable<global::System.Guid> _MessageId;
        partial void OnMessageIdChanging(global::System.Nullable<global::System.Guid> value);
        partial void OnMessageIdChanged();
        /// <summary>
        /// There are no comments for Property User in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        public string User
        {
            get
            {
                return this._User;
            }
            set
            {
                this.OnUserChanging(value);
                this._User = value;
                this.OnUserChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        private string _User;
        partial void OnUserChanging(string value);
        partial void OnUserChanged();
        /// <summary>
        /// There are no comments for Property CreatedDateTime in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        public global::System.DateTimeOffset CreatedDateTime
        {
            get
            {
                return this._CreatedDateTime;
            }
            set
            {
                this.OnCreatedDateTimeChanging(value);
                this._CreatedDateTime = value;
                this.OnCreatedDateTimeChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        private global::System.DateTimeOffset _CreatedDateTime;
        partial void OnCreatedDateTimeChanging(global::System.DateTimeOffset value);
        partial void OnCreatedDateTimeChanged();
        /// <summary>
        /// There are no comments for Property ReadDateTime in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        public global::System.Nullable<global::System.DateTimeOffset> ReadDateTime
        {
            get
            {
                return this._ReadDateTime;
            }
            set
            {
                this.OnReadDateTimeChanging(value);
                this._ReadDateTime = value;
                this.OnReadDateTimeChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        private global::System.Nullable<global::System.DateTimeOffset> _ReadDateTime;
        partial void OnReadDateTimeChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnReadDateTimeChanged();
        /// <summary>
        /// There are no comments for Property Status in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        public global::NotificationODataService.Affra.Service.Notification.Domain.PersonalMessages.PersonalMessageStatus Status
        {
            get
            {
                return this._Status;
            }
            set
            {
                this.OnStatusChanging(value);
                this._Status = value;
                this.OnStatusChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        private global::NotificationODataService.Affra.Service.Notification.Domain.PersonalMessages.PersonalMessageStatus _Status;
        partial void OnStatusChanging(global::NotificationODataService.Affra.Service.Notification.Domain.PersonalMessages.PersonalMessageStatus value);
        partial void OnStatusChanged();
        /// <summary>
        /// There are no comments for Property xmin in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        public long xmin
        {
            get
            {
                return this._xmin;
            }
            set
            {
                this.OnxminChanging(value);
                this._xmin = value;
                this.OnxminChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        private long _xmin;
        partial void OnxminChanging(long value);
        partial void OnxminChanged();
        /// <summary>
        /// There are no comments for Property Message in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        public global::NotificationODataService.Affra.Service.Notification.Domain.PersonalMessages.Message Message
        {
            get
            {
                return this._Message;
            }
            set
            {
                this.OnMessageChanging(value);
                this._Message = value;
                this.OnMessageChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        private global::NotificationODataService.Affra.Service.Notification.Domain.PersonalMessages.Message _Message;
        partial void OnMessageChanging(global::NotificationODataService.Affra.Service.Notification.Domain.PersonalMessages.Message value);
        partial void OnMessageChanged();
    }
    /// <summary>
    /// There are no comments for PersonalMessageStatus in the schema.
    /// </summary>
    public enum PersonalMessageStatus
    {
        Unread = 0,
        Read = 1
    }
    /// <summary>
    /// Class containing all extension methods
    /// </summary>
    public static class ExtensionMethods
    {
        /// <summary>
        /// Get an entity of type global::NotificationODataService.Affra.Service.Notification.Domain.PersonalMessages.Message as global::NotificationODataService.Affra.Service.Notification.Domain.PersonalMessages.MessageSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::NotificationODataService.Affra.Service.Notification.Domain.PersonalMessages.MessageSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::NotificationODataService.Affra.Service.Notification.Domain.PersonalMessages.Message> _source, global::System.Collections.Generic.IDictionary<string, object> keys)
        {
            return new global::NotificationODataService.Affra.Service.Notification.Domain.PersonalMessages.MessageSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::NotificationODataService.Affra.Service.Notification.Domain.PersonalMessages.Message as global::NotificationODataService.Affra.Service.Notification.Domain.PersonalMessages.MessageSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="id">The value of id</param>
        public static global::NotificationODataService.Affra.Service.Notification.Domain.PersonalMessages.MessageSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::NotificationODataService.Affra.Service.Notification.Domain.PersonalMessages.Message> _source,
            global::System.Guid id)
        {
            global::System.Collections.Generic.IDictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "Id", id }
            };
            return new global::NotificationODataService.Affra.Service.Notification.Domain.PersonalMessages.MessageSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::NotificationODataService.Affra.Service.Notification.Domain.PersonalMessages.PersonalMessage as global::NotificationODataService.Affra.Service.Notification.Domain.PersonalMessages.PersonalMessageSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::NotificationODataService.Affra.Service.Notification.Domain.PersonalMessages.PersonalMessageSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::NotificationODataService.Affra.Service.Notification.Domain.PersonalMessages.PersonalMessage> _source, global::System.Collections.Generic.IDictionary<string, object> keys)
        {
            return new global::NotificationODataService.Affra.Service.Notification.Domain.PersonalMessages.PersonalMessageSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::NotificationODataService.Affra.Service.Notification.Domain.PersonalMessages.PersonalMessage as global::NotificationODataService.Affra.Service.Notification.Domain.PersonalMessages.PersonalMessageSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="id">The value of id</param>
        public static global::NotificationODataService.Affra.Service.Notification.Domain.PersonalMessages.PersonalMessageSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::NotificationODataService.Affra.Service.Notification.Domain.PersonalMessages.PersonalMessage> _source,
            global::System.Guid id)
        {
            global::System.Collections.Generic.IDictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "Id", id }
            };
            return new global::NotificationODataService.Affra.Service.Notification.Domain.PersonalMessages.PersonalMessageSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, keys)));
        }
    }
}
namespace NotificationODataService.Default
{
    /// <summary>
    /// There are no comments for Container in the schema.
    /// </summary>
    public partial class Container : global::Microsoft.OData.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new Container object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        public Container(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::Microsoft.OData.Client.ODataProtocolVersion.V4)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
            this.Format.UseJson();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "Affra.Service.Notification.Domain.PersonalMessages", "NotificationODataService.Affra.Service.Notification.Domain.PersonalMessages");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            resolvedType = this.DefaultResolveType(typeName, "Default", "NotificationODataService.Default");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("NotificationODataService.Affra.Service.Notification.Domain.PersonalMessages", global::System.StringComparison.Ordinal))
            {
                return string.Concat("Affra.Service.Notification.Domain.PersonalMessages.", clientType.Name);
            }
            if (clientType.Namespace.Equals("NotificationODataService.Default", global::System.StringComparison.Ordinal))
            {
                return string.Concat("Default.", clientType.Name);
            }
            return clientType.FullName;
        }
        /// <summary>
        /// There are no comments for Message in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::NotificationODataService.Affra.Service.Notification.Domain.PersonalMessages.Message> Message
        {
            get
            {
                if ((this._Message == null))
                {
                    this._Message = base.CreateQuery<global::NotificationODataService.Affra.Service.Notification.Domain.PersonalMessages.Message>("Message");
                }
                return this._Message;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::NotificationODataService.Affra.Service.Notification.Domain.PersonalMessages.Message> _Message;
        /// <summary>
        /// There are no comments for PersonalMessage in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::NotificationODataService.Affra.Service.Notification.Domain.PersonalMessages.PersonalMessage> PersonalMessage
        {
            get
            {
                if ((this._PersonalMessage == null))
                {
                    this._PersonalMessage = base.CreateQuery<global::NotificationODataService.Affra.Service.Notification.Domain.PersonalMessages.PersonalMessage>("PersonalMessage");
                }
                return this._PersonalMessage;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::NotificationODataService.Affra.Service.Notification.Domain.PersonalMessages.PersonalMessage> _PersonalMessage;
        /// <summary>
        /// There are no comments for Message in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        public void AddToMessage(global::NotificationODataService.Affra.Service.Notification.Domain.PersonalMessages.Message message)
        {
            base.AddObject("Message", message);
        }
        /// <summary>
        /// There are no comments for PersonalMessage in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        public void AddToPersonalMessage(global::NotificationODataService.Affra.Service.Notification.Domain.PersonalMessages.PersonalMessage personalMessage)
        {
            base.AddObject("PersonalMessage", personalMessage);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
            private static global::Microsoft.OData.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
            private const string Edmx = @"<edmx:Edmx Version=""4.0"" xmlns:edmx=""http://docs.oasis-open.org/odata/ns/edmx"">
  <edmx:DataServices>
    <Schema Namespace=""Affra.Service.Notification.Domain.PersonalMessages"" xmlns=""http://docs.oasis-open.org/odata/ns/edm"">
      <EntityType Name=""Message"">
        <Key>
          <PropertyRef Name=""Id"" />
        </Key>
        <Property Name=""Id"" Type=""Edm.Guid"" Nullable=""false"" />
        <Property Name=""Subject"" Type=""Edm.String"" />
        <Property Name=""Content"" Type=""Edm.String"" />
        <Property Name=""Extra"" Type=""Edm.String"" />
        <Property Name=""CreatedDateTime"" Type=""Edm.DateTimeOffset"" Nullable=""false"" />
        <Property Name=""CreatedBy"" Type=""Edm.String"" />
        <Property Name=""xmin"" Type=""Edm.Int64"" Nullable=""false"" />
        <NavigationProperty Name=""PersonalMessages"" Type=""Collection(Affra.Service.Notification.Domain.PersonalMessages.PersonalMessage)"" />
      </EntityType>
      <EntityType Name=""PersonalMessage"">
        <Key>
          <PropertyRef Name=""Id"" />
        </Key>
        <Property Name=""Id"" Type=""Edm.Guid"" Nullable=""false"" />
        <Property Name=""MessageId"" Type=""Edm.Guid"" />
        <Property Name=""User"" Type=""Edm.String"" />
        <Property Name=""CreatedDateTime"" Type=""Edm.DateTimeOffset"" Nullable=""false"" />
        <Property Name=""ReadDateTime"" Type=""Edm.DateTimeOffset"" />
        <Property Name=""Status"" Type=""Affra.Service.Notification.Domain.PersonalMessages.PersonalMessageStatus"" Nullable=""false"" />
        <Property Name=""xmin"" Type=""Edm.Int64"" Nullable=""false"" />
        <NavigationProperty Name=""Message"" Type=""Affra.Service.Notification.Domain.PersonalMessages.Message"">
          <ReferentialConstraint Property=""MessageId"" ReferencedProperty=""Id"" />
        </NavigationProperty>
      </EntityType>
      <EnumType Name=""PersonalMessageStatus"">
        <Member Name=""Unread"" Value=""0"" />
        <Member Name=""Read"" Value=""1"" />
      </EnumType>
    </Schema>
    <Schema Namespace=""Default"" xmlns=""http://docs.oasis-open.org/odata/ns/edm"">
      <EntityContainer Name=""Container"">
        <EntitySet Name=""Message"" EntityType=""Affra.Service.Notification.Domain.PersonalMessages.Message"">
          <NavigationPropertyBinding Path=""PersonalMessages"" Target=""PersonalMessage"" />
          <Annotation Term=""Org.OData.Core.V1.OptimisticConcurrency"">
            <Collection>
              <PropertyPath>xmin</PropertyPath>
            </Collection>
          </Annotation>
        </EntitySet>
        <EntitySet Name=""PersonalMessage"" EntityType=""Affra.Service.Notification.Domain.PersonalMessages.PersonalMessage"">
          <NavigationPropertyBinding Path=""Message"" Target=""Message"" />
          <Annotation Term=""Org.OData.Core.V1.OptimisticConcurrency"">
            <Collection>
              <PropertyPath>xmin</PropertyPath>
            </Collection>
          </Annotation>
        </EntitySet>
      </EntityContainer>
    </Schema>
  </edmx:DataServices>
</edmx:Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
            public static global::Microsoft.OData.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
            private static global::Microsoft.OData.Edm.IEdmModel LoadModelFromString()
            {
                global::System.Xml.XmlReader reader = CreateXmlReader(Edmx);
                try
                {
                    global::System.Collections.Generic.IEnumerable<global::Microsoft.OData.Edm.Validation.EdmError> errors;
                    global::Microsoft.OData.Edm.IEdmModel edmModel;
                    
                    if (!global::Microsoft.OData.Edm.Csdl.CsdlReader.TryParse(reader, false, out edmModel, out errors))
                    {
                        global::System.Text.StringBuilder errorMessages = new global::System.Text.StringBuilder();
                        foreach (var error in errors)
                        {
                            errorMessages.Append(error.ErrorMessage);
                            errorMessages.Append("; ");
                        }
                        throw new global::System.InvalidOperationException(errorMessages.ToString());
                    }

                    return edmModel;
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
    }
}
