//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 19/11/2022 12:48:28 AM
namespace ReportODataService.Affra.Service.Report.Domain.Reports
{
    /// <summary>
    /// There are no comments for ReportReceiptSingle in the schema.
    /// </summary>
    public partial class ReportReceiptSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<ReportReceipt>
    {
        /// <summary>
        /// Initialize a new ReportReceiptSingle object.
        /// </summary>
        public ReportReceiptSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new ReportReceiptSingle object.
        /// </summary>
        public ReportReceiptSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new ReportReceiptSingle object.
        /// </summary>
        public ReportReceiptSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<ReportReceipt> query)
            : base(query) {}

    }
    /// <summary>
    /// There are no comments for ReportReceipt in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Id")]
    public partial class ReportReceipt : global::Microsoft.OData.Client.BaseEntityType
    {
        /// <summary>
        /// Create a new ReportReceipt object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="referenceId">Initial value of ReferenceId.</param>
        /// <param name="fileId">Initial value of FileId.</param>
        /// <param name="createdDateTime">Initial value of CreatedDateTime.</param>
        /// <param name="completedDateTime">Initial value of CompletedDateTime.</param>
        /// <param name="status">Initial value of Status.</param>
        /// <param name="xmin">Initial value of xmin.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        public static ReportReceipt CreateReportReceipt(long ID, 
                    global::System.Guid referenceId, 
                    global::System.Guid fileId, 
                    global::System.DateTimeOffset createdDateTime, 
                    global::System.DateTimeOffset completedDateTime, 
                    global::ReportODataService.Affra.Service.Report.Domain.Reports.ReportGenerationStatus status, 
                    long xmin)
        {
            ReportReceipt reportReceipt = new ReportReceipt();
            reportReceipt.Id = ID;
            reportReceipt.ReferenceId = referenceId;
            reportReceipt.FileId = fileId;
            reportReceipt.CreatedDateTime = createdDateTime;
            reportReceipt.CompletedDateTime = completedDateTime;
            reportReceipt.Status = status;
            reportReceipt.xmin = xmin;
            return reportReceipt;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        public long Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        private long _Id;
        partial void OnIdChanging(long value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property ReferenceId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        public global::System.Guid ReferenceId
        {
            get
            {
                return this._ReferenceId;
            }
            set
            {
                this.OnReferenceIdChanging(value);
                this._ReferenceId = value;
                this.OnReferenceIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        private global::System.Guid _ReferenceId;
        partial void OnReferenceIdChanging(global::System.Guid value);
        partial void OnReferenceIdChanged();
        /// <summary>
        /// There are no comments for Property FileId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        public global::System.Guid FileId
        {
            get
            {
                return this._FileId;
            }
            set
            {
                this.OnFileIdChanging(value);
                this._FileId = value;
                this.OnFileIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        private global::System.Guid _FileId;
        partial void OnFileIdChanging(global::System.Guid value);
        partial void OnFileIdChanged();
        /// <summary>
        /// There are no comments for Property CreatedDateTime in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        public global::System.DateTimeOffset CreatedDateTime
        {
            get
            {
                return this._CreatedDateTime;
            }
            set
            {
                this.OnCreatedDateTimeChanging(value);
                this._CreatedDateTime = value;
                this.OnCreatedDateTimeChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        private global::System.DateTimeOffset _CreatedDateTime;
        partial void OnCreatedDateTimeChanging(global::System.DateTimeOffset value);
        partial void OnCreatedDateTimeChanged();
        /// <summary>
        /// There are no comments for Property CompletedDateTime in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        public global::System.DateTimeOffset CompletedDateTime
        {
            get
            {
                return this._CompletedDateTime;
            }
            set
            {
                this.OnCompletedDateTimeChanging(value);
                this._CompletedDateTime = value;
                this.OnCompletedDateTimeChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        private global::System.DateTimeOffset _CompletedDateTime;
        partial void OnCompletedDateTimeChanging(global::System.DateTimeOffset value);
        partial void OnCompletedDateTimeChanged();
        /// <summary>
        /// There are no comments for Property Status in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        public global::ReportODataService.Affra.Service.Report.Domain.Reports.ReportGenerationStatus Status
        {
            get
            {
                return this._Status;
            }
            set
            {
                this.OnStatusChanging(value);
                this._Status = value;
                this.OnStatusChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        private global::ReportODataService.Affra.Service.Report.Domain.Reports.ReportGenerationStatus _Status;
        partial void OnStatusChanging(global::ReportODataService.Affra.Service.Report.Domain.Reports.ReportGenerationStatus value);
        partial void OnStatusChanged();
        /// <summary>
        /// There are no comments for Property xmin in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        public long xmin
        {
            get
            {
                return this._xmin;
            }
            set
            {
                this.OnxminChanging(value);
                this._xmin = value;
                this.OnxminChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        private long _xmin;
        partial void OnxminChanging(long value);
        partial void OnxminChanged();
    }
    /// <summary>
    /// There are no comments for ReportGenerationStatus in the schema.
    /// </summary>
    public enum ReportGenerationStatus
    {
        InProgress = 0,
        Completed = 1,
        Failed = 2
    }
    /// <summary>
    /// Class containing all extension methods
    /// </summary>
    public static class ExtensionMethods
    {
        /// <summary>
        /// Get an entity of type global::ReportODataService.Affra.Service.Report.Domain.Reports.ReportReceipt as global::ReportODataService.Affra.Service.Report.Domain.Reports.ReportReceiptSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::ReportODataService.Affra.Service.Report.Domain.Reports.ReportReceiptSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::ReportODataService.Affra.Service.Report.Domain.Reports.ReportReceipt> _source, global::System.Collections.Generic.IDictionary<string, object> keys)
        {
            return new global::ReportODataService.Affra.Service.Report.Domain.Reports.ReportReceiptSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::ReportODataService.Affra.Service.Report.Domain.Reports.ReportReceipt as global::ReportODataService.Affra.Service.Report.Domain.Reports.ReportReceiptSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="id">The value of id</param>
        public static global::ReportODataService.Affra.Service.Report.Domain.Reports.ReportReceiptSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::ReportODataService.Affra.Service.Report.Domain.Reports.ReportReceipt> _source,
            long id)
        {
            global::System.Collections.Generic.IDictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "Id", id }
            };
            return new global::ReportODataService.Affra.Service.Report.Domain.Reports.ReportReceiptSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, keys)));
        }
    }
}
namespace ReportODataService.Default
{
    /// <summary>
    /// There are no comments for Container in the schema.
    /// </summary>
    public partial class Container : global::Microsoft.OData.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new Container object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        public Container(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::Microsoft.OData.Client.ODataProtocolVersion.V4)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
            this.Format.UseJson();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "Affra.Service.Report.Domain.Reports", "ReportODataService.Affra.Service.Report.Domain.Reports");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            resolvedType = this.DefaultResolveType(typeName, "Default", "ReportODataService.Default");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("ReportODataService.Affra.Service.Report.Domain.Reports", global::System.StringComparison.Ordinal))
            {
                return string.Concat("Affra.Service.Report.Domain.Reports.", clientType.Name);
            }
            if (clientType.Namespace.Equals("ReportODataService.Default", global::System.StringComparison.Ordinal))
            {
                return string.Concat("Default.", clientType.Name);
            }
            return clientType.FullName;
        }
        /// <summary>
        /// There are no comments for ReportReceipt in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::ReportODataService.Affra.Service.Report.Domain.Reports.ReportReceipt> ReportReceipt
        {
            get
            {
                if ((this._ReportReceipt == null))
                {
                    this._ReportReceipt = base.CreateQuery<global::ReportODataService.Affra.Service.Report.Domain.Reports.ReportReceipt>("ReportReceipt");
                }
                return this._ReportReceipt;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::ReportODataService.Affra.Service.Report.Domain.Reports.ReportReceipt> _ReportReceipt;
        /// <summary>
        /// There are no comments for ReportReceipt in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        public void AddToReportReceipt(global::ReportODataService.Affra.Service.Report.Domain.Reports.ReportReceipt reportReceipt)
        {
            base.AddObject("ReportReceipt", reportReceipt);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
            private static global::Microsoft.OData.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
            private const string Edmx = @"<edmx:Edmx Version=""4.0"" xmlns:edmx=""http://docs.oasis-open.org/odata/ns/edmx"">
  <edmx:DataServices>
    <Schema Namespace=""Affra.Service.Report.Domain.Reports"" xmlns=""http://docs.oasis-open.org/odata/ns/edm"">
      <EntityType Name=""ReportReceipt"">
        <Key>
          <PropertyRef Name=""Id"" />
        </Key>
        <Property Name=""Id"" Type=""Edm.Int64"" Nullable=""false"" />
        <Property Name=""ReferenceId"" Type=""Edm.Guid"" Nullable=""false"" />
        <Property Name=""FileId"" Type=""Edm.Guid"" Nullable=""false"" />
        <Property Name=""CreatedDateTime"" Type=""Edm.DateTimeOffset"" Nullable=""false"" />
        <Property Name=""CompletedDateTime"" Type=""Edm.DateTimeOffset"" Nullable=""false"" />
        <Property Name=""Status"" Type=""Affra.Service.Report.Domain.Reports.ReportGenerationStatus"" Nullable=""false"" />
        <Property Name=""xmin"" Type=""Edm.Int64"" Nullable=""false"" />
      </EntityType>
      <EnumType Name=""ReportGenerationStatus"">
        <Member Name=""InProgress"" Value=""0"" />
        <Member Name=""Completed"" Value=""1"" />
        <Member Name=""Failed"" Value=""2"" />
      </EnumType>
    </Schema>
    <Schema Namespace=""Default"" xmlns=""http://docs.oasis-open.org/odata/ns/edm"">
      <EntityContainer Name=""Container"">
        <EntitySet Name=""ReportReceipt"" EntityType=""Affra.Service.Report.Domain.Reports.ReportReceipt"">
          <Annotation Term=""Org.OData.Core.V1.OptimisticConcurrency"">
            <Collection>
              <PropertyPath>xmin</PropertyPath>
            </Collection>
          </Annotation>
        </EntitySet>
      </EntityContainer>
    </Schema>
  </edmx:DataServices>
</edmx:Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
            public static global::Microsoft.OData.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
            private static global::Microsoft.OData.Edm.IEdmModel LoadModelFromString()
            {
                global::System.Xml.XmlReader reader = CreateXmlReader(Edmx);
                try
                {
                    global::System.Collections.Generic.IEnumerable<global::Microsoft.OData.Edm.Validation.EdmError> errors;
                    global::Microsoft.OData.Edm.IEdmModel edmModel;
                    
                    if (!global::Microsoft.OData.Edm.Csdl.CsdlReader.TryParse(reader, false, out edmModel, out errors))
                    {
                        global::System.Text.StringBuilder errorMessages = new global::System.Text.StringBuilder();
                        foreach (var error in errors)
                        {
                            errorMessages.Append(error.ErrorMessage);
                            errorMessages.Append("; ");
                        }
                        throw new global::System.InvalidOperationException(errorMessages.ToString());
                    }

                    return edmModel;
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.7.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
    }
}
